langgraph/prebuilt/tool_executor.py
Needed for streaming in py<3.11
=> patch: add config to ToolExecutor._execute

examples/chat_agent_executor_with_function_calling/human-in-the-loop.ipynb
In this pull request, I've addressed an issue in the human-in-the-loop.ipynb notebook where the input() function was incorrectly used with a keyword argument. I've updated the function call to use a standard string argument, aligning with Python's input() function syntax. This change ensures the notebook runs smoothly without syntax errors and improves code readability. The update has been tested to confirm that the notebook now executes as expected.
=> Update human-in-the-loop notebook with input function fix

README.md
Creates a broken link in the python.langchain.com docs rn
=> chore: readme link

langgraph/graph/state.py
Small typing error I noticed while stepping through the code.
=> Fix typing for _dict_getter

langgraph/__init__.py, langgraph/version.py
=> Add __version__ to langgraph

examples/agent_executor/base.ipynb
this is requiered to load the prompt from hub
=> fix base.ipynb to install langchainhub

pyproject.toml
=> Update pyproject license 

langgraph/prebuilt/agent_executor.py
=> Add tools upport to agentexecutor

langgraph/pregel/__init__.py, langgraph/pregel/read.py, langgraph/pregel/validate.py, tests/test_pregel.py, tests/test_pregel_async.py
- can be replaced by piping to batch method instead
=> Remove subscribe_to_each() method in pregel api

README.md, examples/docs/quickstart.ipynb
=> Update quickstart with simpler message graph examples

langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, tests/memory_assert.py
- This enables building "branching" views of checkpoint history
=> Track parent relationships for checkpoints

langgraph/graph/graph.py, langgraph/graph/state.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py, tests/test_pregel_async.py
=> Adds async conditional edge support

langgraph/graph/graph.py, langgraph/graph/state.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py, tests/test_pregel_async.py
No longer necessary with stream output modes
=> Remove __end__ node from state graph

langgraph/graph/graph.py, langgraph/graph/state.py, tests/test_pregel.py
- prompted by some github issues
=> Add some more docstrings around multi edges

langgraph/checkpoint/base.py
=> Document Checkpoint

examples/multi_agent/multi-agent-collaboration.ipynb
Added packages to be able to run the notebook 
was missing langchain_core langgraph 
also changed that line would run as it was commented out
=> added packages to run multi-agent collaboration notebook

examples/persistence.ipynb, examples/persistence_postgres.ipynb
=> Examples: Add persistence with langchain-postgres

README.md
Fix wrongly written characters
=> docs: fix wrongly written characters

langgraph/graph/graph.py, tests/test_pregel.py
- Move all validation to compile() This allows adding edges before nodes
- Detect more cases of missing edges with shorthand branches
=> Improve graph validation

langgraph/channels/dynamic_barrier_value.py, langgraph/graph/graph.py, langgraph/graph/state.py, langgraph/pregel/__init__.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py, tests/test_pregel_async.py
- This makes it easy to implement graphs where you want to decide among N possible nodes, and then visit another node after whichever one you chose
=> Add `then=` arg for add_conditional_edge and set_conditional_entry_point

langgraph/pregel/__init__.py, langgraph/pregel/debug.py, langgraph/pregel/log.py
- now printing 3 logs per step
- list of nodes about to be executed
- list of state updates returned by nodes
- state checkpoint after updates applied
=> Improve debug logging

langgraph/graph/state.py, langgraph/pregel/__init__.py, langgraph/pregel/write.py, langgraph/utils.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py, tests/test_pregel_async.py
- the function/runnable would be called when processing the state update
=> Fix bug where saving a runnable or function in state object would misbehave

examples/chat_agent_executor_with_function_calling/anthropic.ipynb, langgraph/graph/graph.py, langgraph/utils.py, tests/__snapshots__/test_pregel.ambr
- remove double entry in tracing tree when using functions as nodes
=> Improve tracing output for function nodes

tests/test_pregel_async.py
- when outer invoke/stream is cancelled currently running nodes should be cancelled
- when multiple nodes run in parallel and one fails the others should be cancelled
=> Add tests for async cancellation

langgraph/pregel/__init__.py, langgraph/pregel/debug.py, langgraph/pregel/io.py, langgraph/pregel/types.py, langgraph/pregel/validate.py, tests/test_pregel.py, tests/test_pregel_async.py
- outputs 3 types of payloads
- task: node about to be executed
- task_result: result of node execution
- checkpoint: state values at end of superstep
=> Implement stream_mode=debug

langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, tests/test_pregel.py, tests/test_pregel_async.py
- interface in base checkpointer
- implement in sqlite, aiosqlite, memory
- implement in Pregel.get_state_history()
=> Implement cursor pagination for get_state_history (time travel endpoint)

.github/workflows/link_check.yml, .markdown-link-check.config.json
It's a bit flakey and we don't want to annoy all the linked sites unnecessarily.
=> Markdown Link Check only on changed files

langgraph/channels/base.py, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, langgraph/pregel/types.py, tests/memory_assert.py, tests/test_pregel.py, tests/test_pregel_async.py
- source: input, update or loop
- step: int
- make step counter continue from previous last step
=> Add checkpoint metadata fields

langgraph/channels/base.py, langgraph/checkpoint/__init__.py, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/graph/__init__.py, langgraph/pregel/__init__.py, langgraph/pregel/types.py, tests/__snapshots__/test_pregel.ambr, tests/__snapshots__/test_pregel_async.ambr, tests/memory_assert.py, tests/test_pregel.py, tests/test_pregel_async.py
- Now that checkpoint at end of each step adds no latency there is not point to keep this
- This will make it easier to add future features
=> Remove option to only checkpoint at end of run

poetry.lock, pyproject.toml, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py
- fix waiting for new release of langchain-core
=> Add (failing) test for drawing cyclic edge

examples/introduction.ipynb
- Add imports so each section can be run independently (not depend on previous ones)
- Link to prebuilt stuff to make it easier to look up.
- Fix up printouts
=> Improve Intro

docs/docs/reference/checkpoints.md, docs/mkdocs.yml, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/errors.py
Direct to aiosqlite from sqlite for async
Add errors ref doc page
Fix some callouts and indentation
=> Update Checkpoints Docstrings

docs/docs/concepts/index.md, docs/docs/index.md, docs/docs/tutorials/index.md, docs/mkdocs.yml, examples/chatbot-simulation-evaluation/agent-simulation-evaluation.ipynb, examples/introduction.ipynb
Would benefit from some great images, but I tried to make a decent explainer of the core ideas behind langgraph
=> Add conceptual guide

.github/workflows/link_check.yml, .markdown-link-check.config.json, docs/mkdocs.yml, examples/agent_executor/high-level.ipynb, examples/chat_agent_executor_with_function_calling/high-level-tools.ipynb, examples/chat_agent_executor_with_function_calling/high-level.ipynb, examples/plan-and-execute/plan-and-execute.ipynb
Replace the tool_calling_executor mentions
=> Use create_react_agent

.github/workflows/link_check.yml
429's when we run it, but there's a bug in the filter script rn
=> Pause linkcheck

langgraph/channels/base.py, langgraph/graph/graph.py, langgraph/graph/state.py, langgraph/pregel/__init__.py
=> Small fixes while migrating JS

langgraph/checkpoint/memory.py, langgraph/pregel/__init__.py, tests/test_pregel.py, tests/test_pregel_async.py
- add tests for memory checkpointer list and alist
- fix async step counting
=> Fix memory checkpointer list/alist

langgraph/utils.py, tests/test_utils.py
```
class MyAsyncCallable:
async def __call__(self, state):
...
```
=> Handle Async Callable

examples/lats/lats.ipynb
=> Rm __end__ in lats

langgraph/pregel/__init__.py, langgraph/pregel/retry.py, tests/test_pregel.py, tests/test_pregel_async.py
- default is to not retry, fully configurable
- configuration options follow temporal https://docs.temporal.io/retry-policies#properties
=> Add retry_policy for graphs

examples/chatbot-simulation-evaluation/agent-simulation-evaluation.ipynb, examples/chatbot-simulation-evaluation/langsmith-agent-simulation-evaluation.ipynb, examples/multi_agent/agent_supervisor.ipynb, examples/multi_agent/hierarchical_agent_teams.ipynb, examples/multi_agent/multi-agent-collaboration.ipynb
In a few notebooks, `getpass` call was incorrect resulting in a `TypeError: 'module' object is not callable` error. This PR fixes it.
=> fix: getpass module call

docs/docs/concepts/index.md
- There was a bug in the last code block
- We were still using deprectaed set_entry/finish_point
=> [Conceptual docs] Fixup block

.github/workflows/deploy_docs.yml, docs/docs-requirements.txt, docs/docs/concepts/index.md, docs/mkdocs.yml
=> [Docs] Add analytics

.github/workflows/lint.yml, .github/workflows/test.yml
Turns out lint and test jobs weren't running in main
=> Update ci rules

langgraph/pregel/__init__.py, langgraph/pregel/debug.py, langgraph/pregel/io.py, langgraph/pregel/types.py, tests/test_pregel.py, tests/test_pregel_async.py
- currently output of each node is streamed only when all nodes in that step finish
- checkpoint/values stream chunks still yielded only at the end of the step, as they require applying all updates
=> For stream_mode=updates (the default) stream the output of each node as soon as that node finishes

examples/streaming-tokens.ipynb
=> [Docs] Update stream_tokens to clarify how in older versions of python

examples/streaming-tokens.ipynb
=> [Docs] Stream Anything

examples/branching.ipynb
Related to: https://github.com/langchain-ai/langgraph/discussions/583
=> [Docs] Add explanation for error handling when branching

docs/docs/reference/graphs.md, examples/map-reduce.ipynb, langgraph/constants.py
Also added in start and end since Send is apparently a constant
=> [Docs] Ref docs for Send

langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/managed/few_shot.py, langgraph/pregel/__init__.py, tests/checkpoint/test_aiosqlite.py, tests/checkpoint/test_memory.py, tests/checkpoint/test_sqlite.py, tests/test_pregel.py, tests/test_pregel_async.py
- Combine list and search methods in Checkpointer
=> Expose filter arg in get_state_history

docs/docs/how-tos/index.md, docs/mkdocs.yml
=> docs: fix navigation for passing run time values to tools

examples/multi_agent/hierarchical_agent_teams.ipynb
=> fix: name must not container spaces

langgraph/graph/graph.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py
=> allow path_map keys to be non-strings in add_conditional_edges

langgraph/pregel/retry.py, tests/test_pregel.py, tests/test_pregel_async.py
- Add information about the last exception to retry logging
- Add a few more exceptions to the list not retried by default
=> Adjust default error policy

docs/mkdocs.yml, langgraph/prebuilt/tool_node.py
To impart more clarity on what it expects and returns.
=> Update ToolNode docstring

docs/mkdocs.yml, examples/sdk/js_sdk.ipynb, examples/sdk/python_sdk.ipynb
1. Add JS SDK how-to page
1. Move Python and JS SDK pages under how-to
=> docs: Add JS SDK how-to page

docs/docs/cloud/quick_start.md
1. Update LangGraph Cloud quickstart
=> docs: Update LangGraph Cloud quickstart

docs/docs/cloud/concepts/index.md, docs/mkdocs.yml, examples/cloud_examples/cron_jobs.ipynb, examples/cloud_examples/stateless_runs.ipynb
This is a copy of [this PR](https://github.com/langchain-ai/langgraph/pull/796).
=> docs: Create LangGraph Cloud notebooks for creating cron jobs and stateless runs

docs/docs/cloud/quick_start.md
=> Style nits in quickstart

docs/docs/cloud/quick_start.md
=> Fix misaligned code block

docs/docs/cloud/concepts/index.md, docs/docs/concepts/low_level.md, examples/cloud_examples/human_in_the_loop_user_input.ipynb, examples/cloud_examples/same-thread.ipynb
=> Update intro to same thread example, update conceptual docs to include checkpoint

docs/docs/cloud/deployment/setup.md, docs/docs/cloud/deployment/setup_pyproject.md, docs/mkdocs.yml
=> [Docs] Add pyproject how-to

examples/rewoo/rewoo.ipynb
=> [Docs] spelling

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/langgraph/prebuilt/tool_executor.py, libs/langgraph/langgraph/prebuilt/tool_node.py
- Cleanup parameter formatting
- Add graphs
- Walk through example execution
=> [Docs]  Improve create_react_agent docstring

README.md
=> docs: Add CTA for LangGraph Cloud to README

docs/mkdocs.yml
=> Remove broken edit button, view source button

docs/docs/concepts/low_level.md
replace add_edge by add_conditional_edges
fix a mistake
=> docs: fix typo in low_level.md

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/executor.py, libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/tests/test_pregel_async.py
- first step towards splitting out tick and stream
=> lib: Separate out executor logic from stream methods

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/langgraph/pregel/types.py
- to expose from StateGraph in future PR
=> pregel: Support retry policy per node

docs/docs/reference/checkpoints.md, libs/langgraph/langgraph/checkpoint/aiosqlite.py, libs/langgraph/langgraph/checkpoint/base.py, libs/langgraph/langgraph/checkpoint/memory.py, libs/langgraph/langgraph/checkpoint/sqlite.py
Resolve: https://github.com/langchain-ai/langgraph/issues/1068
=> [Docs] Checkpointer docstrings

libs/langgraph/langgraph/channels/manager.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- this means "fork without update" (eg to rerun a node)
=> Allow call to update_state without values

libs/langgraph/tests/messages.py, libs/langgraph/tests/test_prebuilt.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
This PR works around an issue with pydantic 2.
=> langgraph[patch]: update unit tests to handle AnyStr() for pydantic 2 models

libs/sdk-js/package.json, libs/sdk-js/src/client.mts
- **Improve types for updateState**
- **Bump to 0.0.3**
=> feat(sdk-js): bump to 0.0.3, update types of updateState

docs/mkdocs.yml
Forgot to push this before merging https://github.com/langchain-ai/langgraph/pull/1117
=> docs: update title of doc in sidebar

libs/sdk-js/package.json, libs/sdk-js/src/client.mts, libs/sdk-js/src/schema.ts
- **feat(sdk-js): Add output schema typedef**
- **Expose copy method for thread**
- **Bump to 0.0.4**
=> feat(sdk-js): add output schema to match API, expose copy method for thread

examples/memory/manage-conversation-history.ipynb
=> docs: fix filter_messages error in manage-conversation-history.ipynb

examples/introduction.ipynb
**Title:**
Fix documentation for chatbot node function return value
**Description:**
This PR updates the documentation for the chatbot node function in LangGraph. The new description highlights that the function returns a dictionary containing the updated messages list under the "messages" key. This change aims to make the explanation more Pythonic.
**Request for Shoutout:**
If this PR gets merged, I'd greatly appreciate a shoutout on LinkedIn! Connecting with the community and sharing contributions is 
Here’s my LinkedIn profile: Hassan Memon[https://www.linkedin.com/in/hassan-memon-a109b3257/]. 
always motivating. Thanks in advance!
=> Improved description for chatbot node function

.github/workflows/_test.yml
This will allow running lib tests on checkpointer library test changes.
=> ci: run full test suite on all changes

libs/sdk-js/package.json, libs/sdk-js/src/schema.ts
- **feat(js-sdk): add config and parent_config to thread state schema**
- **Bump to 0.0.5**
=> feat(js-sdk): add config and parent_config to thread state schema

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- move remaining output code from Pregel.stream to PregelLoop
=> Add interrupts and errors to debug stream mode

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/langgraph/tests/any_str.py, libs/langgraph/tests/memory_assert.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Store their string repr instead
=> Don't try to serialize exceptions

examples/multi_agent/agent_supervisor.ipynb
=> docs: fix agent_supervisor.ipynb

docs/docs/cloud/deployment/setup_javascript.md, docs/docs/cloud/faq/studio.md, docs/docs/cloud/how-tos/interrupt_concurrent.md, docs/docs/cloud/quick_start.md, docs/mkdocs.yml
=> patch(docs): Update docs with JS cloud instructions

docs/docs/cloud/how-tos/background_run.md, docs/docs/cloud/how-tos/check_thread_status.md, docs/docs/cloud/how-tos/enqueue_concurrent.md, docs/docs/cloud/how-tos/human_in_the_loop_breakpoint.md, docs/docs/cloud/how-tos/human_in_the_loop_edit_state.md, docs/docs/cloud/how-tos/human_in_the_loop_review_tool_calls.md, docs/docs/cloud/how-tos/human_in_the_loop_time_travel.md, docs/docs/cloud/how-tos/human_in_the_loop_user_input.md, docs/docs/cloud/how-tos/interrupt_concurrent.md, docs/docs/cloud/how-tos/reject_concurrent.md, docs/docs/cloud/how-tos/rollback_concurrent.md, docs/docs/cloud/how-tos/stream_debug.md, docs/docs/cloud/how-tos/stream_events.md, docs/docs/cloud/how-tos/stream_messages.md, docs/docs/cloud/how-tos/stream_multiple.md, docs/docs/cloud/how-tos/stream_updates.md, docs/docs/cloud/how-tos/stream_values.md
- add data to create thread curl commands
- use assistant_id/assistantID everywhere instead of passing in "agent" manually
=> docs: some small fixes

libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_state.py
=> Assert input/output channels aren't managed

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py
- this avoids creating stream values that will be ignored
=> perf: In PregelLoop, only emit stream values requested by caller

docs/docs/concepts/agentic_concepts.md, docs/docs/concepts/low_level.md, docs/docs/concepts/streaming.md, docs/docs/how-tos/many-tools.ipynb, docs/docs/how-tos/memory/manage-conversation-history.ipynb, docs/docs/how-tos/pass-run-time-values-to-tools.ipynb, docs/docs/how-tos/persistence.ipynb, docs/docs/how-tos/react-agent-structured-output.ipynb, docs/docs/how-tos/state-context-key.ipynb, docs/docs/how-tos/state-model.ipynb, docs/docs/how-tos/streaming-tokens.ipynb, docs/docs/tutorials/code_assistant/langgraph_code_assistant.ipynb, docs/docs/tutorials/customer-support/customer-support.ipynb, docs/docs/tutorials/extraction/retries.ipynb, docs/docs/tutorials/introduction.ipynb, docs/docs/tutorials/llm-compiler/LLMCompiler.ipynb, docs/docs/tutorials/plan-and-execute/plan-and-execute.ipynb, docs/docs/tutorials/rag/langgraph_agentic_rag.ipynb, docs/docs/tutorials/rag/langgraph_crag.ipynb, docs/docs/tutorials/rag/langgraph_crag_local.ipynb, docs/docs/tutorials/rewoo/rewoo.ipynb, docs/docs/tutorials/usaco/usaco.ipynb
git grep -l 'https://python.langchain.com/v0.2/docs/' | xargs sed -i 's|https://python.langchain.com/v0.2/docs/|https://python.langchain.com/docs/|g'
=> docs: Update langchain documentation URLs to point at latest version of docs instead of v0.2

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/messages.py, libs/langgraph/langgraph/pregel/types.py, libs/langgraph/tests/fake_chat.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- yields messages token-by-token from LLMs, and any messages returned from a node
- messages are yielded as a tuple of `(message, metadata)`
=> Add stream_mode=messages

libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/types.py, libs/langgraph/langgraph/utils/runnable.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- adds the ability for nodes (including in subgraphs) to emit chunks directly to the output stream, emitted chunks can have any type
- when stream_mode=custom isnt requested by the caller emitted chunks are ignored
=> Add stream_mode=custom

libs/langgraph/langgraph/pregel/messages.py
- running callback handler in background thread could potentially lead to ordering issues
- deduping on `id()` could lead to messages being dropped if they reused memory address of a previous chunk
=> Fix edge cases with stream_mode=messages

libs/langgraph/langgraph/pregel/__init__.py
- If passed it returns a single subgraph, mathching that namespace, if found
=> Add namesapce filter to get_subgraphs

docs/docs/cloud/deployment/cloud.md
Add section about `Deployment Settings`.
=> docs: Update `Deploy to Cloud` docs

libs/checkpoint-postgres/langgraph/store/postgres/aio.py, libs/checkpoint-postgres/langgraph/store/postgres/base.py, libs/checkpoint-postgres/pyproject.toml
In case your cursor loads objects that are not supported by default
=> Custom loads support in postgres checkpointer

libs/checkpoint/langgraph/store/base/__init__.py, libs/checkpoint/tests/test_store.py
This reverts commit cf67acb69978f82b79155b754238995635cc3cbe.
=> Revert "Validate not empty (#1957)"

libs/sdk-js/src/client.ts, libs/sdk-js/src/types.ts
=> fix(js): Add afterSeconds run arg

docs/docs/cloud/reference/api/openapi.json
Adding endpoints for `/subgraphs` and `/store`.
=> docs: Update LangGraph API docs

libs/langgraph/langgraph/pregel/protocol.py, libs/langgraph/langgraph/pregel/remote.py, libs/langgraph/poetry.lock, libs/langgraph/pyproject.toml, libs/langgraph/tests/test_remote_pregel.py
Redo of [this PR](https://github.com/langchain-ai/langgraph/pull/2034) (branched from clean branch).
=> Implement `PregelProtocol` and `RemotePregel` class (attempt 2)

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py
- assert statements are skipped in that case, so we need to move calls to apply_writes to outside assert statements
=> fix: Work w python's O flag

libs/langgraph/langgraph/pregel/__init__.py
=> langgraph: support copy without update in Pregel

libs/langgraph/langgraph/managed/__init__.py, libs/langgraph/langgraph/managed/base.py, libs/langgraph/langgraph/managed/context.py, libs/langgraph/langgraph/managed/is_last_step.py, libs/langgraph/langgraph/managed/shared_value.py, libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/manager.py, libs/langgraph/langgraph/types.py, libs/scheduler-kafka/langgraph/scheduler/kafka/executor.py
- Share step/stop logic with PregelLoop
- Add RemainingSteps value which contains the number of remaining steps
- Switch create_react_agent to use RemainingSteps, so that it behave correctly for return_direct tools
=> Fix IsLastStep counter for runs with checkpointers

docs/docs/tutorials/index.md
Minor formatting update -- since this section stands right now looks quite bad
=> docs: update tutorials index page

docs/docs/concepts/index.md, docs/docs/concepts/langgraph_studio.md, docs/docs/concepts/template_applications.md
Open to adding this as a section of an existing guide as well.
=> docs: document template applications

libs/langgraph/langgraph/pregel/remote.py, libs/langgraph/tests/test_remote_graph.py
=> lib: Ensure RemoteGraph.invoke emits all subgraph events as expected

docs/docs/cloud/reference/cli.md, docs/docs/concepts/langgraph_cli.md
=> fix cli formatting issues

docs/docs/concepts/langgraph_cli.md, docs/docs/concepts/langgraph_server.md, docs/docs/concepts/sdk.md, docs/docs/concepts/streaming.md, docs/docs/how-tos/index.md
- fix broken links
- x
- more link updates
=> docs: fix more broken links

docs/docs/concepts/assistants.md, docs/docs/concepts/langgraph_server.md, docs/docs/concepts/sdk.md
Should resolve all broken links
=> docs: boom

docs/docs/concepts/faq.md
Sync with https://www.langchain.com/langgraph
=> docs: update FAQ

docs/mkdocs.yml
=> docs: update reference layout

docs/docs/cloud/how-tos/webhooks.md
- What triggers webhook request
- What is payload
- How to sign / validate
=> docs: add some detail on webhooks

libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/graph/graph.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Return Control(update_state=, trigger=, send=) from your nodes instead
- Annotate nodes with Control[Literal["destination"]] to see your graph connections drawn
=> lib: Add support for graphs without edges

libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Both for cond edge and edgeless graphs
=> lib: Add test for react architecture using Send + interrupt_before

libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- update_state -> state
- trigger -> goto
=> lib: Rename args in Control object

libs/cli/langgraph_cli/cli.py, libs/cli/tests/unit_tests/test_cli.py
=> cli: add --version option

libs/sdk-js/package.json
Release https://github.com/langchain-ai/langgraph/pull/2370
=> feat(sdk-js): bump to 0.0.22

libs/langgraph/langgraph/pregel/__init__.py
Fixes https://github.com/langchain-ai/langgraph/issues/2380
=> langgraph: add debug to AsyncPregelLoop

docs/docs/tutorials/code_assistant/langgraph_code_assistant.ipynb
Updated the link to the LCEL concept guide
=> docs: Update link to LCEL Concept Guide

.github/workflows/deploy_docs.yml
3rd attempt to fix localhost link
=> docs: fix link checker

docs/docs/how-tos/deploy-self-hosted.md
We need to check later why CI didn't fail with original PR that broke the link
=> docs: fix broken link

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/retry.py
=> lib: Add exception note identify node/task

libs/sdk-js/package.json, libs/sdk-js/src/client.ts, libs/sdk-py/langgraph_sdk/client.py, libs/sdk-py/pyproject.toml
- **feat(sdk): pass cancel on disconnect when joining stream**
- **Bump to 0.0.30**
- **Bump to 0.1.41**
=> feat(sdk): pass cancel on disconnect when joining stream

libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py
=> fixup initial provisioning of aio postgres db

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/tests/conftest.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py
=> Fixup initial provisioning of aio postgres db (#2571)

libs/sdk-py/langgraph_sdk/client.py
Fix typos in langgraph_sdk client.
=> Fix typos in langgraph_sdk client.

docs/docs/cloud/deployment/semantic_search.md, docs/docs/cloud/reference/cli.md, docs/docs/concepts/persistence.md, libs/checkpoint/langgraph/store/base/__init__.py, libs/cli/langgraph_cli/config.py
=> Add Memory Store conceptual doc section

libs/langgraph/langgraph/pregel/__init__.py
- this ensures that config from context vars is merged in
=> lib: Call ensure_config in state crud methods

docs/docs/concepts/template_applications.md, docs/docs/how-tos/deploy-self-hosted.md, docs/docs/tutorials/index.md, docs/docs/tutorials/langgraph-platform/local-server.md
=> docs: Add template quickstart

libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py
- so it works w interrupt_before/after
=> lib: Treat Command as "resuming" signal

docs/docs/how-tos/human_in_the_loop/wait-user-input.ipynb, docs/docs/how-tos/index.md
update index entry
beautify some formatting
=> wait for user input improvements

libs/langgraph/langgraph/prebuilt/tool_node.py
=> langgraph[fix]: pass config to tools

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py
=> checkpoint: set strict_map_key=False in serde

libs/langgraph/langgraph/types.py
=> langgraph: relax type annotation for Command.update

docs/_scripts/generate_api_reference_links.py
Main purpose is to avoid all the repeated log warnings which make the builds hare to understand
=> docs: memoize class resolution

docs/docs/tutorials/customer-support/customer-support.ipynb
=> docs: update tool in customer support tutorial

docs/docs/tutorials/customer-support/customer-support.ipynb
=> Update customer-support.ipynb minor spell

libs/langgraph/langgraph/utils/config.py, libs/langgraph/tests/test_utils.py
Fixes https://github.com/langchain-ai/langgraph/issues/2890
=> langgraph: fix non-empty value check in ensure_config

docs/docs/concepts/index.md
=> docs[patch]: add section headers to LangGraph concepts page

docs/docs/troubleshooting/errors/INVALID_CONCURRENT_GRAPH_UPDATE.md
=> docs: highlight lines in troubleshooting doc

docs/docs/reference/func.md, docs/mkdocs.yml, libs/langgraph/langgraph/func/__init__.py
First pass at the API reference for the functional API
=> functional api: first pass at api reference

docs/docs/concepts/functional_api.md
* Add more patterns
* Some wording
=> more updates to concepts page

docs/_scripts/generate_api_reference_links.py
something is broken with the code anntoations logic regex, can fix independently later on
=> references: remove the code annotations for now

docs/docs/concepts/functional_api.md
Show more entrypoint definitions
=> docs: add more entrypoint defintions

docs/docs/how-tos/deploy-self-hosted.md
=> docs: Add note about how to share Postgres instance for self-hosted deployments

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/tests/test_prebuilt.py
Fixes https://github.com/langchain-ai/langgraph/issues/2875
=> langgraph: allow async state modifier in create_react_agent

libs/langgraph/langgraph/func/__init__.py
=> reference: document entrypoint more

libs/cli/langgraph_cli/docker.py, libs/cli/pyproject.toml, libs/cli/tests/unit_tests/cli/test_cli.py, libs/cli/tests/unit_tests/test_docker.py
Fixes https://github.com/langchain-ai/langgraph/issues/3164
=> fix: missing pgvector in CLI

libs/langgraph/langgraph/func/__init__.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
Remove generator support in entrypoint.
=> functional api: remove generator support

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/tests/test_prebuilt.py
Rename `tool_call_parallelism` (has not been released yet).
=> langgraph[patch]: rename parameter

libs/langgraph/langgraph/graph/graph.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/utils/runnable.py
=> langgraph: update RunnableLike to support injected kwargs

docs/mkdocs.yml
https://mkdocstrings.github.io/reference/handlers/base/
=> Update inv file

.github/workflows/deploy_docs.yml, docs/Makefile, docs/_scripts/generate_llms_text.py
=> publish llms text

libs/langgraph/langgraph/graph/message.py, libs/langgraph/tests/test_messages_state.py
Port: https://github.com/langchain-ai/langgraphjs/pull/846
=> fix(langgraph): Dedupe input (right-side) messages in add_messages

libs/sdk-js/src/client.ts, libs/sdk-js/src/utils/async_caller.ts
Reverts portion of https://github.com/langchain-ai/langgraph/pull/2993
=> fix(sdk-js): non-ok response is not throwing anymore

libs/sdk-js/.gitignore, libs/sdk-js/langchain.config.js, libs/sdk-js/package.json, libs/sdk-js/src/client.ts, libs/sdk-js/src/react/debug.tsx, libs/sdk-js/src/react/index.ts, libs/sdk-js/src/react/stream.tsx, libs/sdk-js/src/types.messages.ts, libs/sdk-js/src/types.ts, libs/sdk-js/tsconfig.json, libs/sdk-js/yarn.lock
Experimental `useStream` React hook to make streaming as simple as possible. Supports branching / forking, message-tuple stream mode for rendering messages.
Usage: https://github.com/langchain-ai/langchain-nextjs-template/pull/62
=> feat(sdk-js): add experimental useStream hook

.github/workflows/deploy_docs.yml, docs/Makefile, docs/_scripts/generate_llms_text.py, docs/_scripts/notebook_hooks.py, docs/docs/how-tos/state-reducers.md, docs/tests/unit_tests/test_highlights.py
* Add testing step to to docs build pipeline
* Requires updating import structure in some place
* Add simple unit test to cover some logic with highlights
=> docs: add unit tests to build pipeline

libs/checkpoint/langgraph/store/base/batch.py
- while loop w asyncio.sleep(0) takes up cpu
=> Fix busy loop in AsyncBatchedBaseStore

libs/cli/langgraph_cli/cli.py, libs/cli/langgraph_cli/config.py, libs/cli/tests/unit_tests/cli/test_cli.py, libs/cli/tests/unit_tests/test_config.py
- Now supporting local dependencies in directories that are not contained in the docker context (ie. outside the folder containing langgraph.json)
- This is achieved by passing each parent directorty as an additional context to docker build
- This makes it a lot easier to build projects contained in monorepos where you need to include some sibling/parent folder as a dependency
- Also include additional comments in the generated dockerfile to delimit each section
=> cli: Add support for dependencies in parent directories

libs/cli/langgraph_cli/docker.py, libs/sdk-py/pyproject.toml
Related to https://github.com/langchain-ai/langgraph/issues/1319
=> fix(cli): use '{{json .}}' format instead of 'json'

libs/langgraph/langgraph/graph/state.py
Hi, I am a student and was going through the tutorial. While trying to understand the different components by reading the docstring found this super minor typo 😄 . I hope to contribute more meaningful changes in future 😸
=> Very minor typo in docstring of State -> add_node

docs/_scripts/generate_api_reference_links.py, docs/_scripts/notebook_hooks.py
* Temporarily revert. Need to add unit tests tomorrow and can then restore
=> docs: revert changes to api reference generation

libs/cli/examples/my_app.py, libs/cli/langgraph_cli/cli.py, libs/cli/langgraph_cli/config.py, libs/cli/poetry.lock, libs/cli/pyproject.toml, libs/cli/tests/unit_tests/graphs/agent.py, libs/cli/tests/unit_tests/test_config.json, libs/cli/tests/unit_tests/test_config.py
Right now requires that the file be in one of the local packages/dependencies.
=> Support http config

docs/_scripts/third_party_page/packages.yml
Here: 
https://github.com/langchain-ai/open_deep_research
=> Update packages w/ Open Deep Research

docs/docs/cloud/how-tos/webhooks.md
1. Provided additional context on webhook usage and setup.
2. Structured supported endpoints into a table for better readability.
=> Improved Webhooks documentation with good formatting and readability

docs/docs/concepts/human_in_the_loop.md
=> docs(concepts) : update human_in_the_loop.md

libs/langgraph/langgraph/pregel/validate.py
OK not including as well, but this was useful for troubleshooting as a new user (especially before there were any examples)
=> pregel: update validation error messages

libs/langgraph/langgraph/pregel/messages.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- any messages seen in inputs in on_chain_start should not be emitted
=> langgraph: stream_mode=messages should not emit input or state messages

libs/sdk-py/langgraph_sdk/client.py
=> sdk-py: fix docstring for runs.list

libs/langgraph/langgraph/func/__init__.py
Uncovered while working on #3670. Feel free to close if too minor to merge.
=> chore: whitespace cleanup

libs/sdk-py/langgraph_sdk/client.py
Fixes https://github.com/langchain-ai/langgraph/issues/3644
=> sdk-py: fix decode_json in sdk

.github/workflows/ci.yml, libs/cli/generate_schema.py, libs/cli/langgraph_cli/config.py, libs/cli/poetry.lock, libs/cli/pyproject.toml, libs/cli/schemas/schema.json, libs/cli/schemas/schema.v0.json
So you have cute IDE autocomplete / language server checking.
=> Add json schema to CLI

libs/langgraph/tests/test_pregel.py
- Now tests a model with inherited fields
=> Make pydntic input test stricter

libs/checkpoint/langgraph/store/base/__init__.py, libs/checkpoint/pyproject.toml
Mainly relevenat for the in memory store.
=> Ensure key is string

libs/sdk-js/package.json, libs/sdk-js/src/react-ui/index.ts, libs/sdk-js/src/react-ui/server/server.ts, libs/sdk-js/src/react-ui/types.ts, libs/sdk-js/src/react/stream.tsx
- merge `typedUi.create` and `typedUi.write` into `typedUi.push`
- Add mutate function in `onCustomEvent`
=> feat(sdk-js): api improvements for gen ui

libs/langgraph/tests/test_pregel_async.py
While working on langchain-ai/langgraphjs#984 I ported the test I was debugging over to python so I could compare behavior. Figured I might as well add it to this codebase, as I don't think we had this particular case covered previously.
=> chore(langgraph): add functional api test for multiple task interrupts

docs/docs/how-tos/create-react-agent-memory.ipynb
Fixed a typo in create-react-agent-memory.ipynb
=> docs: Correct a typo in create-react-agent-memory.ipynb

libs/langgraph/bench/__main__.py, libs/langgraph/bench/sequential.py
Performance is poor due to state graph utilizing n^2 entries right now to accommodate Command. Adding benchmark prior to updating implementation.
=> benchmarks: add sequential graph of a few hundred nodes

libs/langgraph/bench/__main__.py
- Now that we're a lot faster on this case, we can enable some larger test cases
=> Enable larger cases of sequential bench graph

libs/langgraph/langgraph/graph/schema_utils.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_pregel_async.py
- pydantic will do that for us if needed
=> Schema coercer should never throw

libs/cli/README.md
=> docs: Update bad link in libs/cli README.md

libs/langgraph/pyproject.toml
Includes:
- Explicit unsetting of runnable context var
- Weakref for PregelExecutableTask
both to reduce the chance of keeping a reference to an internal object and preventing garbage collection
=> Release 0.3.18

docs/docs/concepts/high_level.md, docs/docs/tutorials/code_assistant/langgraph_code_assistant.ipynb, docs/docs/tutorials/workflows/index.md
Anthropic links for blog post and docs are failing CI -- 
https://github.com/langchain-ai/langgraph/actions/runs/14024926642/job/39261981682
Remove to unblock docs build; we may add back to ignore later.
=> Remove failing links

libs/sdk-py/langgraph_sdk/client.py
Propagate headers in the async client
=> sdk-py: Propagate headers in the async client

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/checkpoint/pyproject.toml
=> Handle Sends

docs/_scripts/third_party_page/packages.yml
=> docs: remove langmanus temporarily

libs/langgraph/langgraph/pregel/runner.py
- For exceptions raised in user code (ie. nodes or edges) remove internal frames from the stack trace
=> Remove internal frames from stack traces

libs/langgraph/langgraph/pregel/algo.py
- many times these aren't actually used, so makes sense to delay creation until needed
=> Lazily create atomic counters in pregel scratchpad

docs/docs/tutorials/introduction.ipynb
"Copy the clipboard" doesn't return valid Python code.
=> docs: fixed indentation

libs/cli/pyproject.toml
Release to pick up this: https://github.com/langchain-ai/langgraph/pull/4164
=> cli: release 0.1.89

libs/cli/langgraph_cli/config.py, libs/cli/pyproject.toml, libs/cli/tests/unit_tests/cli/test_cli.py, libs/cli/tests/unit_tests/test_config.py
After user installs, removes pip, setuptools, and wheel from the resulting image.
=> Remove pip from image

docs/docs/cloud/how-tos/use_stream_react.md
=> updates prereq banner

libs/cli/langgraph_cli/cli.py, libs/cli/langgraph_cli/config.py, libs/cli/tests/unit_tests/cli/test_cli.py, libs/cli/tests/unit_tests/test_config.py
- Uses new `install-node.sh` script already used for Python Gen UI
- Add default `node_version` / `python_version` based on provided `graphs`
Closes #4115
=> feat(cli): add multiplatform support

libs/langgraph/langgraph/graph/branch.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/utils/runnable.py
- attached to every node to handle command/send return values
- used to be a full blown conditional edge, can be simpler by doing all of it in a single function
=> Simplify path for control branch attached to every node

libs/langgraph/bench/fanout_to_subgraph.py, libs/langgraph/langgraph/func/__init__.py, libs/langgraph/langgraph/graph/branch.py, libs/langgraph/langgraph/graph/graph.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/call.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/pregel/write.py, libs/langgraph/langgraph/utils/runnable.py, libs/langgraph/tests/test_large_cases.py
- call it less often
- find the run from the run manager at callsite
=> Reduce perf impact of set_context

docs/docs/tutorials/workflows/index.md
Make the docs clearer within the prompt chaining section
=> docs: rename parallel_workflow --> prompt_chaining_workflow

docs/docs/agents/context.md
=> docs(agents); context page

docs/docs/agents/human-in-the-loop.md
* Updated overview to stress that HIL can async (sin't required to be real-time)
* Added some code annotations
* Added a figure
* Broke the code cells into smaller ones since the full one was difficult to understand (at least for me)
=> docs(hil): minor tweaks

docs/docs/agents/run_agents.md
=> docs(agents): running agents

libs/langgraph/langgraph/graph/schema_utils.py, libs/langgraph/tests/test_pregel.py
If the state schema uses validators, skip the model construct optimization.
For context, pydantic state can be significantly slower to run than typed dict and dataclass states due to the full recursive validation.
We have some optimizations to reduce the impact of this (using cached validators with model_construct), but this doesn't handle things like field_validator.
We prefer correctness over performance, obviously.
Resolves: https://github.com/langchain-ai/langgraph/issues/4074
=> Use model_validate if needed

libs/sdk-js/package.json, libs/sdk-js/src/client.ts, libs/sdk-py/langgraph_sdk/client.py, libs/sdk-py/pyproject.toml
Removes default from https://github.com/langchain-ai/langgraph/pull/4362
=> fix: threads search sorting defaults

libs/langgraph/langgraph/pregel/messages.py, libs/langgraph/tests/test_pregel.py
=> langgraph: fix messages streaming for list of Commands

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_large_cases_async.py, libs/langgraph/tests/test_pregel_async.py
Fix issue found in https://github.com/langchain-ai/langgraph/pull/4374#discussion_r2056701206
=> Fix double interrupt return caused by dynamic tasks

docs/mkdocs.yml
=> docs: Adds additional Google Analytics tag to docs

libs/langgraph/langgraph/graph/branch.py, libs/langgraph/langgraph/graph/graph.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/draw.py, libs/langgraph/tests/__snapshots__/test_large_cases.ambr, libs/langgraph/tests/__snapshots__/test_pregel.ambr, libs/langgraph/tests/test_pregel.py
- Don't draw unexpected edges to END node
- If a conditional edge has a custom label for END node then draw it
=> Improve logic for drawing virtual end node

libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py
Fine if command is "empty" as we don't add writes for mapped resumes.
=> langgraph: fix bug + add test for multi resume

docs/_scripts/notebook_convert.py, docs/_scripts/notebook_convert_templates/mdoutput/index.md.j2, docs/tests/unit_tests/test_notebook_conversion.py
Handle a small thing that can be fairly confusing to new python users.
Before:
After:
=> docs: process cell magics

docs/docs/cloud/how-tos/generative_ui_react.md, libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/graph/ui.py, libs/langgraph/langgraph/pregel/messages.py, libs/langgraph/tests/test_pregel.py, libs/sdk-js/src/react-ui/index.ts, libs/sdk-js/src/react-ui/server/server.ts, libs/sdk-js/src/react-ui/types.ts
- Add docs about (partial) streaming UI components from LLMs
- Add missing support for "nostream" in LangGraph
=> feat(ui): add `merge` option to UI messages

docs/docs/concepts/streaming.md, docs/docs/how-tos/streaming.md
easter eggs can be added later when no one is watching
=> docs: make streaming not as fun

docs/docs/cloud/reference/api/openapi.json
Incorporate new arguments added to the API, including the `/mcp` paths
=> Update openapi spec

docs/docs/cloud/concepts/cron_jobs.md, docs/docs/cloud/concepts/runs.md, docs/docs/cloud/concepts/threads.md, docs/docs/cloud/concepts/webhooks.md, docs/docs/concepts/langgraph_cli.md, docs/docs/concepts/langgraph_server.md, docs/docs/concepts/sdk.md, docs/mkdocs.yml
- Edited the CLI overview
- Edited the SDK overview
- Edited the Server overview
- Created stub overview pages for cron jobs, runs, threads, and webhooks
=> docs: Rework CLI/SDK/Server overviews

docs/docs/cloud/deployment/setup.md, docs/docs/cloud/deployment/setup_javascript.md, docs/docs/cloud/deployment/setup_pyproject.md, docs/docs/concepts/application_structure.md, docs/mkdocs.yml
Small wording updates to the application structure documentation pages.
=> docs: Update application structure pages

docs/docs/how-tos/http/custom_lifespan.md, docs/docs/how-tos/http/custom_middleware.md, docs/docs/how-tos/http/custom_routes.md, docs/mkdocs.yml
Small changes to Server Customization section.
=> docs: Small changes to Server Customization section

docs/docs/tutorials/get-started/1-build-basic-chatbot.md, docs/docs/tutorials/get-started/2-add-tools.md, docs/docs/tutorials/get-started/3-add-memory.md, docs/docs/tutorials/get-started/4-human-in-the-loop.md, docs/docs/tutorials/get-started/5-customize-state.md, docs/docs/tutorials/get-started/6-time-travel.md, docs/snippets/chat_model_tabs.md
- Add to LangGraph basics
- Also fix some NameErrors
=> docs: chat model tabs

docs/docs/tutorials/get-started/2-add-tools.md, docs/docs/tutorials/get-started/4-human-in-the-loop.md
Reverts langchain-ai/langgraph#4631
=> Revert "docs: fix some links"

docs/mkdocs.yml
Hide example temporarily until we bring it up to date
=> docs: remove customer support bot example

docs/docs/cloud/deployment/self_hosted_control_plane.md, docs/docs/cloud/deployment/self_hosted_data_plane.md, docs/docs/concepts/deployment_options.md, docs/docs/concepts/langgraph_self_hosted_control_plane.md, docs/docs/concepts/langgraph_self_hosted_data_plane.md
@lnhsingh, let me know if you're ok with this copy and messaging placement.
=> docs: Update beta labels for deployment options

README.md, libs/langgraph/README.md
=> docs: All that power

docs/docs/troubleshooting/errors/INVALID_CHAT_HISTORY.md, docs/docs/troubleshooting/errors/INVALID_GRAPH_NODE_RETURN_VALUE.md, docs/docs/tutorials/auth/add_auth_server.md, docs/docs/tutorials/auth/getting_started.md
Hi,
As per titles, fixing some issues in docs. See commit diffs for details.
Best,
Didier
=> Removing spelling mistakes

CONTRIBUTING.md, docs/docs/cloud/concepts/webhooks.md, docs/docs/cloud/deployment/self_hosted_data_plane.md, docs/docs/cloud/how-tos/configuration_cloud.md, docs/docs/cloud/how-tos/cron_jobs.md, docs/docs/cloud/how-tos/datasets_studio.md, docs/docs/cloud/how-tos/generative_ui_react.md, docs/docs/cloud/how-tos/use_threads.md
Hi,
As PR title says, fixing some typos in documentation files
Best,
Didier
=> Fixing some typos

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py
- The validation isn't worth the cost of having to pass list of nodes to task config
=> Remove local_write utility

docs/docs/how-tos/graph-api.ipynb, libs/langgraph/langgraph/graph/state.py
Following up on https://github.com/langchain-ai/langgraph/pull/4269
=> docs: deferred nodes

docs/docs/tutorials/langgraph-platform/local-server.md, libs/langgraph/uv.lock, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/pyproject.toml, libs/prebuilt/tests/__snapshots__/test_react_agent_graph.ambr, libs/prebuilt/tests/test_react_agent_graph.py, libs/prebuilt/uv.lock, libs/scheduler-kafka/uv.lock
needs review tomorrow morning when my brain is a bit fresher
Toggle for mermaid diagrams for each combo of `tools`, `pre_model_hook`, `post_model_hook`, and `response_format`...
<details>
<summary>Basic Agent</summary>
```mermaid
graph TD;
__start__ --> agent;
agent --> __end__;
```
</details>
<details>
<summary>Agent with tools</summary>
```mermaid
graph TD;
__start__ --> agent;
agent -.-> __end__;
agent -.-> tools;
tools --> agent;
```
</details>
<details>
<summary>Agent with pre_model_hook</summary>
```mermaid
graph TD;
__start__ --> pre_model_hook;
pre_model_hook --> agent;
agent --> __end__;
```
</details>
<details>
<summary>Agent with tools and pre_model_hook</summary>
```mermaid
graph TD;
__start__ --> pre_model_hook;
agent -.-> __end__;
agent -.-> tools;
pre_model_hook --> agent; …
```
=> prebuilts hitl: fix branching logic + add structural snapshot tests

docs/_scripts/generate_llms_text.py
A first pass at the script to fix the immediate issue. Will follow up with a few additional improvements.
=> docs: Add script to generate llms-txt links from yaml

docs/_scripts/generate_llms_text.py
Update llms.txt based on content
=> docs: improve llms.txt to generate title and description based on content

docs/mkdocs.yml
see vid with before and after
https://github.com/user-attachments/assets/b71eed2d-d65d-4a53-99b9-d86f7f23ee51
=> docs: fix top nav

docs/docs/cloud/deployment/self_hosted_control_plane.md, docs/docs/cloud/deployment/self_hosted_data_plane.md, docs/docs/concepts/deployment_options.md, docs/docs/concepts/langgraph_self_hosted_control_plane.md, docs/docs/concepts/langgraph_self_hosted_data_plane.md
=> docs: Add note about Enterprise plan in banner for all self-hosted deployment options.

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/test_react_agent.py
Fixes https://github.com/langchain-ai/langgraph/issues/4841
=> fix: `post_model_hook` should inject state + store into tool calls if necessary

docs/docs/reference/pregel.md, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/tests/test_pregel.py
- Replaced by NodeBuilder introduced in earlier PR
=> Remove Channel node builder

docs/docs/tutorials/rag/langgraph_adaptive_rag.ipynb
Fix https://github.com/langchain-ai/langgraph/issues/3848
=> docs: fix pprint import

docs/docs/concepts/low_level.md, libs/langgraph/langgraph/graph/state.py
=> docs: remove usage of `StateGraph(dict)`

docs/docs/concepts/subgraphs.md
The state while defining the Subgraph is updated (it was previously mentioned wrongly - as the same State class of the main graph). Also an edge connecting START to the call_model node in the subgraph was created.
=> docs: Update subgraphs.md

docs/docs/cloud/how-tos/studio/manage_assistants.md
Reverts langchain-ai/langgraph#5058
=> Revert "fix assistants overview link"

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/validate.py
- This has never been used and is not useful or intended functionality
=> Remove support for node reading a single managed value

libs/cli/langgraph_cli/config.py, libs/cli/pyproject.toml, libs/cli/schemas/schema.json, libs/cli/schemas/schema.v0.json, libs/cli/tests/unit_tests/test_config.py, libs/cli/uv.lock
Let you manually specify raw `pip` if you prefer
=> feat: Customizable Pip Installer

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/shallow.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py
- This should definitely be removed soon, but let's give people more time to update
=> Restore shallow checkpointer

libs/checkpoint-postgres/uv.lock, libs/checkpoint-sqlite/uv.lock, libs/langgraph/langgraph/pregel/runner.py, libs/prebuilt/uv.lock
=> If FuturesDict callback has been GCed, don't call it

.github/workflows/deploy_docs.yml
This reverts commit aedf974dfd7e4297ac6edb5a9a81624249abd822.
=> Revert "docs: deploy from v0 branch for now (#4960)"

.github/workflows/deploy_docs.yml
This reverts commit a7ea5e44ce12e3618d1a766587163afbfe424e04.
=> Reapply "docs: deploy from v0 branch for now (#4960)" (#5184)

docs/docs/agents/mcp.md, docs/docs/concepts/server-mcp.md, docs/mkdocs.yml
=> docs: update mcp docs

docs/docs/agents/models.md, docs/snippets/chat_model_tabs.md
* Expand chat model documentation a bit. 
* Adds links to langchain docs to make relevant information easier to find.
* This is a stop-gap until we merge langchain and langgraph docs
=> docs: consolidate models

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/utils/queue.py, libs/langgraph/tests/test_pregel.py
- This is more flexible version of the debug= flag, which we'll deprecate
=> Add print_mode= arg to invoke/stream

docs/docs/concepts/langgraph_standalone_container.md
=> add warning about serverless

libs/sdk-js/package.json
Bumping JS SDK to release updated message types.
=> Bump js sdk to 0.0.89

docs/docs/concepts/langgraph_control_plane.md
=> docs: Add note about preemptive compute infra

docs/docs/concepts/template_applications.md
Closes https://github.com/langchain-ai/langgraphjs/issues/1331
=> fix(docs): invalid command for creating langgraph app

docs/docs/cloud/reference/langgraph_server_changelog.md
Automated changelog update.
This PR was created by the LangGraph Changelog Bot.
=> docs: [LangGraph Changelog Bot] Changelog updates for new version(s)

docs/docs/cloud/reference/langgraph_server_changelog.md
Automated changelog update created by the LangGraph Server Changelog Bot.
Feel free to merge anytime.
=> docs: [LangGraph Server Changelog Bot] Changelog updates for new version(s)

docs/docs/cloud/deployment/self_hosted_data_plane.md
This param is not needed anymore
=> docs: fix langgraph dataplane docs

libs/prebuilt/langgraph/prebuilt/tool_node.py
Improve documentation in ToolNode module
=> docs(prebuilt): improve documentation in ToolNode module

libs/prebuilt/Makefile, libs/prebuilt/tests/conftest.py
=> chore(prebuilt): Allow testing fast

docs/docs/concepts/low_level.md, docs/docs/how-tos/graph-api.md
=> chore(docs): Mention dataclass

docs/docs/cloud/how-tos/webhooks.md
Add information about disabling webhooks
=> feat(docs): Document disabling webhooks

docs/docs/cloud/deployment/egress.md, docs/docs/cloud/deployment/self_hosted_control_plane.md, docs/docs/cloud/deployment/standalone_container.md
=> docs: add egress docs for LGP self hosted

docs/docs/cloud/deployment/self_hosted_control_plane.md
Thank you for contributing to LangGraph! Follow these steps to mark your pull request as ready for review. **If any of these steps are not completed, your PR will not be considered for review.**
- Examples:
- feat(core): add multi-tenant support
- fix(cli): resolve flag parsing error
- docs(openai): update API usage examples
- Allowed `{TYPE}` values:
- feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert, release
- Allowed `{SCOPE}` values (optional):
- langgraph, docs, cli, checkpoint, checkpoint-postgres, checkpoint-sqlite, prebuilt, scheduler-kafka, sdk-py
- Once you've written the title, please delete this checklist item; do not include it in the PR.
- **Description:** a description of the change. Include a [closing …
=> docs: fix egress formatting

docs/docs/cloud/how-tos/generative_ui_react.md
Fixes https://github.com/langchain-ai/langgraph/issues/5311
=> feat(docs): add python alt for UI how to

libs/cli/pyproject.toml, libs/cli/uv.lock
new CLI version with support for api-version flag
=> release(cli): Release new CLI version with support for api-version flag

docs/docs/tutorials/get-started/1-build-basic-chatbot.md, docs/docs/tutorials/get-started/2-add-tools.md, docs/docs/tutorials/get-started/3-add-memory.md, docs/docs/tutorials/get-started/4-human-in-the-loop.md
Fix pages on get started guide
=> chore(docs): Fix pages on get-started tab

docs/docs/how-tos/graph-api.md
=> fix(docs): extended examples in graph API docs

docs/Makefile, docs/docs/how-tos/multi_agent.md
=> chore(docs): fix js build

docs/docs/concepts/auth.md, docs/docs/concepts/low_level.md, docs/docs/how-tos/auth/custom_auth.md
=> chore(docs): fix more admonitions

docs/docs/agents/agents.md
=> fix(docs): update agents.md

libs/langgraph/langgraph/graph/_branch.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/types.py
Send should inherit from hashable, and need to use Sequence since List is invariant.
https://github.com/langchain-ai/langgraph/issues/5850
=> fix: mypy issue with conditional edges

docs/docs/agents/multi-agent.md, docs/docs/concepts/mcp.md, docs/docs/how-tos/graph-api.md, docs/docs/how-tos/multi_agent.md, docs/docs/how-tos/subgraph.md
Related Linear ticket: https://linear.app/langchain/issue/DOC-51/add-js-translations-for-remaining-pages
=> chore(docs): add remaining js translations

libs/langgraph/langgraph/types.py, libs/langgraph/tests/conftest.py, libs/langgraph/tests/test_pregel.py
Thank you for contributing to LangGraph! Follow these steps to mark your pull request as ready for review. **If any of these steps are not completed, your PR will not be considered for review.**
- Examples:
- feat(core): add multi-tenant support
- fix(cli): resolve flag parsing error
- docs(openai): update API usage examples
- Allowed `{TYPE}` values:
- feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert, release
- Allowed `{SCOPE}` values (optional):
- langgraph, docs, cli, checkpoint, checkpoint-postgres, checkpoint-sqlite, prebuilt, scheduler-kafka, sdk-py
- Once you've written the title, please delete this checklist item; do not include it in the PR.
- **Description:** a description of the change. Include a [closing …
=> fix: Persist resume_map values

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/langgraph/prebuilt/tool_node.py, libs/prebuilt/tests/test_tool_node.py
* Add structured output tools to ToolNode
* Fix default tool node name to match the actual default ('tools')
* Update doc-strings to explain what inputs/outputs are for the ToolNode.
* Mark internal attributes as private (potentially breaking -- although hopefully users aren't accessing these)
* OK with two properties? Done since users may be relying on `tools_by_name` and expanding the return type will break user code.
* Make `tools_by_name` an official public property
* Make `structured_output_tools` a public property
There should be no reason why users are accessing these attributes
```python
_tool_to_state_args
_tool_to_store_arg
_handle_tool_errors
_messages_key
```
```python
class OutputSchema(BaseModel):
name: str
age: int
location: str
tool_node = ToolNode([OutputSchema])
assert …
```
=> feat(prebuilt): Add structured output tools to ToolNode

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py
Quick clean up to simplify the logic by which messages into the model are prepared.
=> chore(prebuilt): Separate prompt from model

docs/docs/concepts/plans.md
**Description:** updates sales team links to point to our form.
**Issue:** DOC-170 (internal Linear ticket)
=> fix(docs): update sales links 

libs/langgraph/langgraph/pregel/remote.py, libs/langgraph/pyproject.toml, libs/langgraph/tests/test_remote_graph.py, libs/langgraph/uv.lock, libs/prebuilt/uv.lock
Fix baggage propagation for opt-in distributed tracing when no additional headers are provided.
=> fix(langgraph): Remote Baggage

docs/docs/cloud/reference/api/openapi.json
This PR updates the OpenAPI specification with changes detected from the LangGraph API server.
**Changes detected as of LangGraph API version 0.2.137**
This update was automatically generated by the sync workflow in the langgraph-api repository.
=> chore(cli): Update OpenAPI spec from LangGraph API v0.2.137

libs/langgraph/tests/__snapshots__/test_large_cases.ambr, libs/langgraph/tests/conftest.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_large_cases_async.py, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/__snapshots__/test_react_agent_graph.ambr, libs/prebuilt/tests/test_deprecation.py, libs/prebuilt/tests/test_react_agent.py, libs/prebuilt/tests/test_response_format.py
* revert change of `agent` node to `model`
* revert removal of pydantic agent states + agent state consolidation
* revert removal of `version` arg
* revert removal of backwards compat `config_schema`
=> chore(prebuilt): revert unnecessary breaking changes

docs/docs/cloud/reference/api/openapi.json
This PR updates the OpenAPI specification with changes detected from the LangGraph API server.
**Changes detected as of LangGraph API version 0.4.8**
This update was automatically generated by the sync workflow in the langgraph-api repository.
=> chore(docs): Update OpenAPI spec from LangGraph API v0.4.8

libs/sdk-py/langgraph_sdk/client.py
So it renders nicer in the ref docs.
=> chore(sdk-py): Cleanup docstring indentation

libs/checkpoint-sqlite/tests/test_sqlite.py
**Description:** 
Add test for before and limit parameters  for the list in SqliteSaver which was marked as TODO.
=> test: Add tests for before and limit parameters for list SqliteSaver

libs/cli/tests/unit_tests/test_util.py
Added unit tests for util.py.
Authored by @oumizx. Had to copy #6113 into this separate PR because langgraph/libs/cli was having issues with secrets.
=> test(cli): add tests for util.py

libs/langgraph/pyproject.toml, libs/langgraph/uv.lock, libs/prebuilt/uv.lock
- Bump langgraph version from 0.6.8 to 0.6.9
=> chore(langgraph): bump version
