langgraph/graph/state.py, langgraph/pregel/__init__.py, langgraph/pregel/write.py
- this removes one unnamed run from langsmith trace for each node, and ensures that output is streamed from each node to folks listening to that w stream_events
=> Remove double channelwrite

examples/rewoo/rewoo.ipynb
The way the current implementation works, the solver never has access to the tools results, only to the steps and the question.
This is because the replacement process only updates the references in the tool input not on the results.
For example, without this change, the prompt we give to the solver is:
```
prompt
Solve the following task or problem. To solve the problem, we have made step-by-step Plan and retrieved corresponding Evidence to each Plan. Use them with caution since long evidence might contain irrelevant information.
Plan: Calculate the square root of 342142. 
#E1 = calculate[square root of 342142]Plan: Calculate 23 to the power of 2. 
#E2 = calculate[23 to the power of 2]Plan: Multiply #E1 by #E2. 
#E3 = calculate[584.9290555272494 multiplied by 529]
Now solve the question …
```
=> Fixed rewoo.ipynb

langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, tests/memory_assert.py, tests/test_pregel.py, tests/test_pregel_async.py
- Add Pregel.get_state_history and .aget_state_history methods to get history iterator
- Update checkpointer base class with new list and get_tuple methods
- Rewrite in-memory checkpointer class to track history
- Rewrite sqlite and aiosqlite checkpointers to track history
- Add new tests for history tracking
=> Add history tracking to in-memory, sqlite and aiosqlite checkpointers

langgraph/pregel/__init__.py, langgraph/pregel/debug.py
- ensures that order of updates sent to channels is independent of timing differences when parallel executing multiple nodes
- enables future features
=> Collect pending writes for each node separately

langgraph/channels/any_value.py, langgraph/channels/base.py, langgraph/channels/binop.py, langgraph/channels/context.py, langgraph/channels/ephemeral_value.py, langgraph/channels/last_value.py, langgraph/channels/named_barrier_value.py, langgraph/channels/topic.py, tests/test_channels.py
- clearer name
- channels with complex data structures in checkpoint (eg a set or list) now copy the checkpointed data structures before creating the new channel
=> Rename BaseChannel.empty() to BaseChannel.from_checkpoint()

langgraph/graph/graph.py, langgraph/pregel/__init__.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py
- The less frames in library code the less confused the user is
- This doesn't remove all library frames (not possible), but it's a start
=> Remove some noisy frames from stack traces

langgraph/pregel/__init__.py, langgraph/pregel/io.py, tests/test_pregel.py, tests/test_pregel_async.py
This PR addresses a specific issue where a graph unexpectedly returns None for falsy values instead of the actual falsy output. This behavior was identified during operations where the expected behavior is to output falsy values, such as 0, False, or an empty collection, but instead, the graph outputs None.
The issue is illustrated with the following example:
```python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain_core.runnables import RunnableLambda
>>> from langgraph.graph import Graph, END
>>> workflow = Graph()
>>> workflow.add_node('minus1', RunnableLambda(lambda n: n-1))
>>> workflow.set_entry_point('minus1')
>>> workflow.add_edge('minus1', …
```
=> Pregel: Add support for falsy outputs in Pregel class

langgraph/checkpoint/__init__.py, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, tests/memory_assert.py
- Remove pydantic usage from base checkpointer class
- Make serialization configurable for all existing checkpointer classes, you can eg use dill or json instead of pickle
=> Make ser/de configurable in checkpointer classes

examples/plan-and-execute/plan-and-execute.ipynb
This pull request resolves issue in https://github.com/langchain-ai/langchain/discussions/20158
Error:
```
---> [23](vscode-notebook-cell:?execution_count=22&line=23)     if state["response"]:
[24](vscode-notebook-cell:?execution_count=22&line=24)         return True
[25](vscode-notebook-cell:?execution_count=22&line=25)     else:
KeyError: 'response'
```
Changes: Check if `response` exists in state
=> fix: plan execute example response state

langgraph/pregel/__init__.py, langgraph/pregel/io.py, tests/test_pregel.py, tests/test_pregel_async.py
- (unrelated) use run_id passed in
- if using a graph as node in another graph ensure stream_mode for inner call is always values
- ensure langchain-core doesn't auto promote streamed dicts to addable dicts, which results in unexpected output (only) when calling astream_events
=> Fix astream_events modifying output format unexpectedly

langgraph/pregel/__init__.py
The following error will occur when retrieving state (`StateGraph`) on an empty channel.
```python
async def aget_state(self, config: RunnableConfig) -> StateSnapshot:
if not self.checkpointer:
raise ValueError("No checkpointer set")
saved = await self.checkpointer.aget_tuple(config)
checkpoint = saved.checkpoint if saved else empty_checkpoint()
config = saved.config if saved else config
async with AsyncChannelsManager(self.channels, checkpoint) as channels:
_, next_tasks = _prepare_next_tasks(
checkpoint, self.nodes, channels, for_execution=False
)
values = read_channels(channels, self.stream_channels_list)
return StateSnapshot(
>               values[self.stream_channels]
if isinstance(self.stream_channels, str)
else values,
tuple(name for name, _ in next_tasks),
config,
)
E …
```
=> Default state value (`StateGraph`) to `None` if channel is empty

examples/rag/langgraph_rag_agent_llama3_local.ipynb
For the GPT4AllEmbeddings to work (in the Indexing part) the `gpt4all` package is required. This PR adds it to the list of required dependencies at the top of the notebook
=> Add required `gpt4all` dependency

examples/multi_agent/hierarchical_agent_teams.ipynb
In the `hierarchical_agent_teams.ipynb` example, `research_graph` should be replaced by `authoring_graph` during compilation.
=> Fix/call the correct variable `authoring_graph` during compilation

langgraph/pregel/__init__.py, langgraph/pregel/validate.py, tests/test_pregel.py, tests/test_pregel_async.py
- channels must be declared in the constructor args
=> Pregel: Remove implicit creation of channels referenced by nodes

langgraph/checkpoint/aiosqlite.py
If you're adding tables to the same connection that you use for the checkpointer, this line raises an error (since you will have already had to `await conn`
=> Check if conn is alive

langgraph/checkpoint/base.py, langgraph/pregel/__init__.py, tests/test_pregel.py, tests/test_pregel_async.py
- This adds a historic view of the actions taken by nodes inside a thread, supporting rendering a richer history of a thread (eg in debug ui)
=> Add writes property in checkpoint metadata

examples/learning.ipynb, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/managed/base.py, langgraph/managed/few_shot.py, langgraph/pregel/__init__.py, langgraph/pregel/read.py, tests/checkpoint/test_aiosqlite.py, tests/checkpoint/test_memory.py, tests/checkpoint/test_sqlite.py, tests/test_pregel.py, tests/test_pregel_async.py
This PR is a reimplementation of the [old "Add FewShotExamples managed value" PR](https://github.com/langchain-ai/langgraph/pull/332). A new PR is created because there are merge conflicts with the old PR. The changes in this PR are mostly derived from the old PR with a few noted exceptions.
1. Add `score` field to `CheckpointMetadata`. Clients can specify a score for a checkpoint to mark a thread as "good". This is different from the old PR.
1. Add `search()` and `asearch()` APIs to `BaseCheckpointSaver` for searching checkpoints by metadata without filtering on `thread_id`. Implement the APIs in `MemorySaver`, `SqliteSaver`, and `AsyncSqliteSaver`. The implementation is mostly copied from the `list()` method. The old PR implemented an API called `list_w_score()`.
1. Copy …
=> Add `FewShotExamples` managed value (redo)

langgraph/channels/base.py, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/base.py, langgraph/checkpoint/memory.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, poetry.lock, pyproject.toml, tests/checkpoint/test_aiosqlite.py, tests/checkpoint/test_memory.py, tests/checkpoint/test_sqlite.py, tests/memory_assert.py, tests/test_pregel.py, tests/test_pregel_async.py
- this avoids conflicts if multiple processes creating checkpoints in same thread at same time
- uuid6 with a monotically increasing clock_seq is sortable by creation time at ms precision (plus clock_seq for ties, plus 48 bits of randomness for further ties)
=> Use uuid6 as the id for checkpoints

Makefile, docs/_scripts/copy_notebooks.py, examples/async.ipynb, examples/chat_agent_executor_with_function_calling/dynamically-returning-directly.ipynb, examples/customer-support/customer-support.ipynb, examples/human-in-the-loop.ipynb, examples/persistence.ipynb, examples/streaming-tokens.ipynb, examples/time-travel.ipynb
It still makes sense to be verbose-yet-transparent I think so that the how-tos remain generally applicable. However ,for people coming from the AgentExecutor, this admonition will point them to the easier high level constructor
=> Add pointers to create_react_agent in how-tos where appropriate

langgraph/channels/ephemeral_value.py, langgraph/checkpoint/aiosqlite.py, langgraph/checkpoint/sqlite.py
This matches the LangGraphJS implementation: https://github.com/langchain-ai/langgraphjs/blob/main/langgraph/src/checkpoint/sqlite.ts#L41
=> Enable WAL mode in `SqliteSaver` and `AsyncSqliteSaver`

langgraph/managed/few_shot.py, langgraph/pregel/__init__.py, tests/test_pregel.py, tests/test_pregel_async.py
`Callable` metadata filters are used for filtering on checkpoint metadata that is only known at runtime. For example, in OpenGPTs, an `assistant_id` (an instance of a graph), is only known after it is created. In this scenario, a developer should define a function that retrieves the `assistant_id` from the passed `RunnableConfig`.
1. Update `FewShotExamples` to support passing a `Callable` metadata filter.
1. ???
1. Update `langgraph` version in LangGraph API after this feature is merged and released.
1. Update OpenGPTs, pass function to `FewShotExamples` for filtering checkpoint metadata by `assistant_id`.
=> Add support for passing `Callable` metadata filter to `FewShotExamples` managed value

docs/_scripts/copy_notebooks.py, docs/docs/tutorials/index.md, docs/mkdocs.yml
LangGraph docs shouldn't have docs that are duplicates of an existing how-to that just use a different provider.
=> [Docs] Rm Integration Tutorial

docs/docs/concepts/index.md
1. Delete some unnecesary "'s".
2. Add some missing periods.
3. Improve typo like "Behind the seens".
4. Add missing "```python".
5. Replace "pydantic" by "Pydantic".
=> docs: fix multiple typos on conceptual guides

langgraph/pregel/__init__.py, tests/memory_assert.py, tests/test_pregel.py, tests/test_pregel_async.py
The following scenario occurs in OpenGPTs/LangChain API, which is what prompted this change.
1. Thread run is posted and graph execution is interrupted before tool execution.
2. Inspecting the thread's checkpoint metadata shows that `graph_id` and `assistant_id` are present in the checkpoint metadata. This is correct an expected.
3. Resume graph execution (i.e. post another thread run with null input).
4. Inspecting the thread's checkpoint metadata shows that `graph_id` and `assistant_id` are NOT present in the checkpoint metadata. This is unexpected.
The solution/feature to accommodate this scenario is to merge a run's configurable fields with the previous checkpoint config (if any). This ensures that when a graph resumes execution from an interrupt, it should contain the configurable …
=> Merge configurable fields with previous checkpoint config before each run

README.md, docs/docs/concepts/index.md
- Emphasize by explicitly stating that configurables are added to LangSmith as metadata. I spent hours trying different solutions here before I discovered that this was possible.
- Add link to conceptual guides in readme
=> docs: specify that configurables are added to LangSmith as metadata

langgraph/utils.py
When invoking an async graph using the sync API
Closes: #547
=> More Descriptive TypeError

langgraph/pregel/__init__.py, langgraph/pregel/debug.py, tests/test_pregel.py, tests/test_pregel_async.py
- reorganize checkpointing code to share code between input and step checkpoints
- do not emit debug/checkpoint events when there is no checkpointer attached
- emit debug/checkpoint event for input checkpoint as well
=> Add metadata to debug/checkpoint stream events

langgraph/constants.py, langgraph/serde/jsonplus.py, tests/memory_assert.py, tests/test_jsonplus.py, tests/test_pregel.py
- any invalid utf-8 chars now removed on dumps
- fix serialization of Send
- remove serialization of NamedTuple, which doesn't work
- add test for custom serde passed to memory saver
- add test using Send and JsonPlus serde
=> serde: Handle unicode issues when encoding

langgraph/checkpoint/sqlite.py, tests/checkpoint/test_sqlite.py
The nesting had made these methods unbound at some point.
Addresses #597 to the extent that we are able, since stdlib sqlite doesn't support async
=> Nicer NotImplementedError in sqlite checkpointer

docs/docs/reference/graphs.md
seems mkdocs stops inferring a ToC if you insert a H1
=> Fixup ToC in ref doc

examples/pass-run-time-values-to-tools.ipynb
Fix typo in how-to guide for run time tools.
=> docs: fix typo in how to guide for binding run time values to tools

langgraph/channels/base.py, langgraph/channels/dynamic_barrier_value.py, langgraph/channels/named_barrier_value.py, langgraph/pregel/__init__.py, tests/test_pregel.py
- This introduces a new optional method BaseChannel.consume, which gets called when a channel triggers a node
- This is an alternative place to clean up channel state, in addition to the existing pattern of clearing state in the update() call for the next step
- Channels should implement consume() when they want to clean up state exactly if and only if the channel triggered a node
- Channels should clean up state in update() when they instead need to guarantee their value is available for a single step, irrespective of whether it was actually read
=> Fix for update_state mistakenly resetting barrier channels

langgraph/graph/graph.py, tests/__snapshots__/test_pregel.ambr, tests/test_pregel.py, tests/test_state.py
Plus fix a small bug.
Previously, we validated that nodes explicitly route to END.
This feels a bit unnecessary, since graphs are expected to keep processing until no work is left to be done
This decision is a bit of a 1-way door, since once we relax it, if we change our minds, it would break otherwise working code. LMK if you have reservations
=> Accept dead-ends

langgraph/channels/binop.py, tests/test_pregel.py
- this makes List/Sequence annotations behave same as list
=> In Binop channels unwrap types before trying to instantiate

langgraph/channels/base.py, langgraph/channels/manager.py, langgraph/checkpoint/base.py, langgraph/checkpoint/sqlite.py, langgraph/managed/few_shot.py, langgraph/pregel/__init__.py, tests/checkpoint/test_aiosqlite.py, tests/checkpoint/test_memory.py, tests/checkpoint/test_sqlite.py
- default is incrementing integers, starting at 1
- now support using str/int/float as versions, as long as they are monotically increasing
=> Allow checkpointer to customize assignment of channel versions

langgraph/channels/any_value.py, langgraph/channels/base.py, langgraph/channels/binop.py, langgraph/channels/context.py, langgraph/channels/dynamic_barrier_value.py, langgraph/channels/ephemeral_value.py, langgraph/channels/last_value.py, langgraph/channels/named_barrier_value.py, langgraph/channels/topic.py, langgraph/checkpoint/sqlite.py, langgraph/pregel/__init__.py, tests/test_channels.py, tests/test_pregel.py, tests/test_pregel_async.py
- previously when channels were cleared via update([]) or consume() that would not bump the version
- that behavior is not compatible with checkpointers that store blobs separately, which join checkpoint and blobs using version
- now update() and consume() return bool to indicate if version should be bumped
- this also avoids bumping version when nothing changed
=> Version all channel changes

docs/docs/cloud/reference/sdk/js_ts_sdk_ref.md, libs/sdk-js/.gitignore, libs/sdk-js/README.md, libs/sdk-js/package.json, libs/sdk-js/tsconfig.json, libs/sdk-js/yarn.lock
`typedoc` is used to generate documentation for the public entry points of the JS/TS SDK and `concat-md` is used to consolidate the documentation files into a single markdown file. This is done for simplicity; it keeps the MkDocs navigation simple.
This approach isn't ideal (the docs aren't easily customizable and they don't look amazing), but it's a starting point and gets the job done. Minimal effort to generate docs and all important classes, interfaces, and types are documented with references back to the source code.
=> docs: Create JS/TS SDK reference page

docs/docs/cloud/index.md
The LangGraph Cloud home page is modeled off the LangGraph home page.
=> docs: Update Cloud home page

docs/docs/cloud/concepts/index.md, docs/docs/cloud/index.md, docs/docs/cloud/reference/api/api_ref.html, docs/docs/cloud/reference/api/api_ref.md, docs/docs/cloud/reference/api/openapi.json, docs/docs/cloud/reference/api_ref.md, docs/mkdocs.yml
The API reference page is the same Scalar API site that's hosted in each LangGraph Cloud deployment. For simplicity, the Scalar API site is linked from the MkDocs site because it has its own navigation and styling.
=> docs: Update LangGraph Cloud API reference page to link to Scalar API site

docs/docs/cloud/deployment/cloud.md, docs/docs/cloud/deployment/self_hosted.md, docs/docs/cloud/deployment/setup.md, docs/mkdocs.yml
1. Move `Deployment` pages under `How-to Guides`.
1. Create how-to page for how to set up a LangGraph application for deployment.
1. Create how-to page for how to deploy to LangGraph Cloud.
=> docs: Create how-to for setting up LangGraph app and how-to for deploying to LangGraph Cloud

docs/docs/cloud/deployment/studio.md, docs/mkdocs.yml
1. Create how-to page for LangGraph Studio basics.
=> docs: Add how-to page for LangGraph Studio

libs/cli/langgraph_cli/docker.py, libs/cli/tests/unit_tests/test_cli.py
Will wait until the corresponding LangSmith PR will land
=> chore(cli): use different container port for debugger

docs/docs/cloud/deployment/self_hosted.md, docs/docs/cloud/deployment/setup.md
The how-to page for self-hosted LangGraph Cloud mostly refers to the `README` of the public Helm chart. GitHub links are pending...
=> docs: Update self-hosted how-to page for LangGraph Cloud

libs/langgraph/langgraph/graph/graph.py, libs/langgraph/tests/test_pregel.py
When an instance of a callable class is passed as the path arg to add_conditional_edges but no path_map is provided, get_type_hints(path) is called, which raises a TypeError (since get_type_hints only accepts a module, class, method, or function).
This patch fixes the error by trying to get type hints from path.\_\_call\_\_ first, which should work for instances of callable classes.
Tested: Added a test that raises TypeError without the fix in this patch but passes with the fix.
=> Fix bug in add_conditional_edges when no path_map is provided

libs/langgraph/langgraph/checkpoint/aiosqlite.py
In AsyncSqliteSaver, otherwise your program will "hang".
Recommend using 
```python
async with AsyncSqliteSaver.from_conn_str(...) as checkpointer:
graph = builder.compile(checkpointer=...)
```
=> [Docstrings] Add reminder to close connection

examples/rag/langgraph_crag.ipynb
small typo in the langgraph_crag tutorial notebook.
=> docs: fix typo in langgraph crag tutorial notebook

libs/cli/README.md, libs/cli/langgraph_cli/cli.py
The digest SHA of the base image should be output for debugging purposes when running `langgraph build`.
Example output:
```
(env) andrewnguonly@Andrews-MBP examples % langgraph build -t langgraph-libs-cli-examples:1 
- Pulling...+ docker pull langchain/langgraph-api:3.11
- Pulling...3.11: Pulling from langchain/langgraph-api
\ Pulling...Digest: sha256:5aad40e6635aee3e91a1254bf0ad26bb8b5021b3d65a56e0e0a5720f2555ef46
Status: Downloaded newer image for langchain/langgraph-api:3.11
docker.io/langchain/langgraph-api:3.11
...
```
=> cli: set verbose flag for pull in langgraph build

libs/langgraph/langgraph/checkpoint/aiosqlite.py, libs/langgraph/langgraph/checkpoint/base.py, libs/langgraph/langgraph/checkpoint/memory.py, libs/langgraph/langgraph/checkpoint/sqlite.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Whenever a node finishes, checkpoint pending writes
=> lib: Checkpoint pending writes whenever a node finishes

docs/overrides/main.html
Leaves more space for code.
Before:
After:
=> Remove Jupyter cell 'In[<number>]' display column from docs

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/tests/test_interruption.py
We noticed that it is currently not possible to interrupt a graph multiple times.
Once the graph resumes execution after an interruption, it just continues executing, ignoring `interrupt_before` and `interrupt_after`.
The reason is that after resuming this condition in `_should_interrupt` seems to always return false:
```
any(
checkpoint["channel_versions"].get(chan, null_version)
> seen.get(chan, null_version)
for chan in snapshot_channels
)
```
In this PR I added a unit test in `test_interruption.py` to spec the desired behavior. I modified the code to pass the unit test, but since I do not understand what this code does it's probably not the right thing.
It would be great to get some guidance on how to fix this properly.
=> Support multiple interruptions after resuming execution

docs/overrides/main.html
Hide indented output columns as well
=> Hide output spacer column in docs

docs/docs/cloud/deployment/cloud.md, docs/docs/cloud/deployment/setup_pyproject.md, docs/docs/cloud/deployment/test_locally.md
There are a lot of build errors in LangGraph Cloud. Typos in package names, dependency conflicts, etc. Adding a note to the docs to suggest building the app locally before deploying to LangGraph Cloud. Hopefully, this reduces some of the build errors in LangGraph Cloud.
=> docs: Add instructions to test locally before deploying to Cloud

libs/langgraph/langgraph/channels/binop.py
When using forward refs, inline lambdas in Annotated are re-evaluated for every subclass, thus making the comparison fail
=> Don't include lambdas in __eq__ for BinOp

libs/langgraph/langgraph/graph/state.py
It looks like a typo to me: `END` should be `START`.
`END` should be accepted as `end_key` and it is accepted with the `super` call path.
=> Fix StateGraph.add_edge end_key check

libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- cond edge will run for each execution of Send, so target channels need to support multiple publishes
Fixes https://github.com/langchain-ai/langgraph/discussions/1157
=> Fix issue when cond edge visited after multiple executions of Send

examples/visualization.ipynb
`NodeColors` does not exist anymore in[ Langchain_core ](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/runnables/graph.py) -> updated to `NodeStyles` and changed the param names. 
Comment:
- Additional point I noticed is that the graph outputs do not match the code. Let me know if it's intentional or you want me to fix it.
=> fix: update the function for node colors

libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py
=> checkpoint-postgres: fix setup for AsyncPostgresSaver

examples/persistence_postgres.ipynb
1. According to the [make start-postgres](https://github.com/langchain-ai/langgraph/blob/main/libs/checkpoint-postgres/Makefile#L8) command in the context, execute docker compose, and the configured port is [5441](https://github.com/langchain-ai/langgraph/blob/main/libs/checkpoint-postgres/tests/compose-postgres.yml#L5).
1. remove unuse import
=> docs: fix persistence_postgres.ipynb

examples/introduction.ipynb
**PR Details:**
This PR corrects a minor typo in the documentation, changing "they agent's course" to "their agent's course" for clarity and consistency.
---
**Hi [LangGraph/LangChain Team Member’s Name],**
I’m excited to share that I recently contributed to the LangChain project and am now contributing to the LangGraph Docs. If possible, could you give me a shoutout on LinkedIn? It would mean a lot and might inspire others to contribute as well.
Here’s my LinkedIn profile: [Hassan Memon](https://www.linkedin.com/in/hassan-memon-a109b3257/).
Thank you for your support and for fostering such a great platform for learning and collaboration. I look forward to contributing more in the future!
Best regards,  
Hassan Memon
=> Fix typo in documentation: corrected 'they agent's' to 'their agent's'

libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/tests/test_pregel.py
- LangGraph Studio 0.0.12 (0.0.12)
- langgraph 0.2.3
This is a real example from running my `graph` with a bug in one of the nodes.
```python
langgraph-api-1       | Retrying task Generate Data Schema after 0.23 seconds (attempt 2) after AttributeError 'dict' object has no attribute 'project_id'
langgraph-api-1       | Run Error
```
```python
langgraph-api-1       | Retrying task Generate Data Schema after 0.23 seconds (attempt 2) due to:
AttributeError: 'dict' object has no attribute 'project_id'
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/retry.py", line 74, in arun_with_retry
async for _ in task.proc.astream(task.input, task.config):
File "/usr/local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3287, in …
```
=> Include exception traceback in run_with_retry logging

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/managed/base.py, libs/langgraph/langgraph/managed/is_last_step.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/types.py, libs/langgraph/tests/any_str.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Save errors produced by tasks, under pending_writes
- Re-work logic to cancel other tasks when one fails, ready to change for interrupt exception
- Update serializer to handle exceptions
- Update get_state/get_state_history with new return value property "tasks" which contains a richer description of the next tasks, currently with id, name and error (if already ran and errored)
=> Checkpoint errors in pending_writes, expose under StateSnapshot.tasks

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py, libs/checkpoint/langgraph/checkpoint/memory/__init__.py
- Previously implementations were clearing only tasks if the index matched a previously saved one, which isn't enough to guarantee idempotency
=> checkpoint-*: In put_writes clear any previously saved writes for this task_id

libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_state.py
fix: #1331
I used `inspect.signature` to read the name of the first parameters and determine whether this variable has a type_hint.
And used `StopIteration` to prevent situations where there are no parameters.
Although in this situation, executing invoke will still result in an error.
If want to catch errors before running the graph, maybe you can check that the number of parameters is not zero?
=> langgraph: fix add_node input schema error

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py, libs/checkpoint/langgraph/checkpoint/base/__init__.py, libs/checkpoint/langgraph/checkpoint/memory/__init__.py, libs/checkpoint/langgraph/checkpoint/serde/types.py, libs/langgraph/langgraph/errors.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/any_str.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- put_writes(error) should not prevent saving future successful if task is retried successfully
- put_writes(writes) should be a no-op if non-error writes already exist for that task (this prevents tasks executed more than once from modifying writes previously saved / acted on)
- checkpoints should not include channel default values (ie those without a version)
- list() should fetch and return writes for each checkpoint
=> Fix semantics of put_writes/list

docs/docs/cloud/reference/api/api_ref.md
Added a section to the API reference to clarify that calling the API requires the `X-Api-Key` header. I think this is the most appropriate place in the docs to put this information.
=> docs: Add section about authentication to API reference

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py
In the current version of `create_react_agent`, execution cannot be halted when a tool exception occurs. Instead, exceptions are intercepted and passed to the agent as text in a `ToolMessage`. This differs from the `AgentExecutor`, which does not handle exceptions and leaves tool error handling to the tools themselves.
To address this limitation, `create_react_agent` signature is adjusted to take `ToolNode` in the `tools` argument, which allows modifying how tool errors are handled
=> Allow passing `ToolNode` as `tools` in `create_react_agent`

docs/docs/cloud/how-tos/interrupt_concurrent.md
Correct parameter in client.runs.create is "multitask_strategy" not "multitask_strategychrom"
=> [docs]: fix parameter "multitask_strategy" misspelled

libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- if we use the raw input we can end up saving keys that were actually ignored (because not one of the input keys), which is incosistent
=> For input checkpoint use filtered input writes in checkpoint metadata

examples/llm-compiler/LLMCompiler.ipynb
Reference to https://github.com/langchain-ai/langgraph/issues/1565 ,
Related issues: https://github.com/langchain-ai/langgraph/issues/1513 and https://github.com/langchain-ai/langgraph/issues/1459
This bug fix is an extension of this PR: [1444](https://github.com/langchain-ai/langgraph/pull/1444/files#diff-552f25122adeb48c8f6671a7add98adf73598c57907e9ebfe6c1187c6a0a26e0R656), which fixed the same issue but missed this instance of it.
- The function _parse_joiner_output has been changed to always have a return type of Dict {"messages": ...}, as expected
- An example has been added to show off the Replan functionality
=> docs: Fix Replan action failing due to incorrect format

libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py, libs/langgraph/tests/test_pregel_async.py
- These are needed when subgraphs are invoked synchronously in nodes
=> checkpoint: Implement sync methods in async checkpointers

libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py, libs/langgraph/Makefile, libs/langgraph/poetry.lock, libs/langgraph/pyproject.toml, libs/langgraph/tests/__snapshots__/test_pregel_async.ambr, libs/langgraph/tests/conftest.py, libs/langgraph/tests/test_channels.py, libs/langgraph/tests/test_interruption.py, libs/langgraph/tests/test_prebuilt.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/langgraph/tests/test_state.py, libs/langgraph/tests/test_store.py, libs/langgraph/tests/test_utils.py
- This more closely remembers the environment they're used in, so it's what we should be testing
- Remove unnecessary pytest-asyncio dependency, use anyio pytest plugin instead
- Convert remaining async tests using only memory checkpointer to use all existing ones
=> test: Ensure that async checkpointers in tests are setup in same event loop as they are used in

libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py, libs/langgraph/tests/test_pregel.py
- Otherwise when used in multiple subgraphs in parallel separate queries can interfere w each other
Closes #1586
=> Use a lock for all operations on sqlite checkpointer

libs/langgraph/langgraph/graph/graph.py
This change will result in the LangGraph API `GET /assistants/<id>/graph` endpoint returning the updated `before,after` (comma separated) value. Clients (e.g. LangGraph Studio) will be able to parse this string and render appropriate UI controls.
Clients that are using the `__interrupt` field will need to migrate to support comma separated value in this field.
=> Return `before,after` for `__interrupt` metadata if both interrupts are configured for a node

docs/docs/cloud/deployment/setup_pyproject.md
1. fix: Point the reference repo to `langgraph-example-pyproject`
1. fmt
=> docs: Correct the reference repo in the `Cloud - Setup App (pyproject.toml)` documents

libs/langgraph/langgraph/prebuilt/tool_node.py, libs/langgraph/tests/test_prebuilt.py
This pull request adds support for pydantic v1 state to the ToolNode class. The `ToolNode` class now accepts an additional input type `BaseModel` for the `input` parameter in the `_func` and `_afunc` methods.
=> Add support for pydantic v1 state to ToolNode

examples/human_in_the_loop/dynamic_breakpoints.ipynb
I corrected a typo in the document, changing "NodeInterupt" to "NodeInterrupt".
=> docs: fix typo `NodeInterupt`

libs/langgraph/langgraph/prebuilt/tool_node.py
Avoid type incompatibility when using `add_node` to add a `ToolNode`.
=> refactor: Type narrowing for ToolNode.name

libs/scheduler-kafka/README.md, libs/scheduler-kafka/langgraph/scheduler/kafka/default_async.py, libs/scheduler-kafka/langgraph/scheduler/kafka/executor.py, libs/scheduler-kafka/langgraph/scheduler/kafka/orchestrator.py, libs/scheduler-kafka/langgraph/scheduler/kafka/types.py
- Define protocol for sync and async producer and consumer
- Accept consumer/producer as init args in Orchestrator/Executor
- If not passed in, create default consumer/producer as before
=> kafka: Make consumer and producer classes configurable

libs/scheduler-kafka/langgraph/scheduler/kafka/executor.py, libs/scheduler-kafka/langgraph/scheduler/kafka/orchestrator.py, libs/scheduler-kafka/langgraph/scheduler/kafka/types.py, libs/scheduler-kafka/tests/drain.py, libs/scheduler-kafka/tests/test_fanout.py, libs/scheduler-kafka/tests/test_fanout_sync.py, libs/scheduler-kafka/tests/test_subgraph.py, libs/scheduler-kafka/tests/test_subgraph_sync.py
- Enables attaching a list of messages (topic/key/value) to send when run finishes
=> kafka: Expose finally_send as public api

.github/workflows/_integration_test.yml, .github/workflows/_lint.yml, .github/workflows/bench.yml, libs/langgraph/bench/__main__.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/utils/config.py, libs/langgraph/langgraph/utils/runnable.py
- Avoid creating new callback manager when received one as arg
- Avoid looking for config when already received one as arg
- Avoid copies of values in ensure_config/merge_configs
- Implement version of ensure_config that accepts multiple configs (avoids calling merge_configs first)
- Avoid calling merge_configs when we only need to attach extra tags/metadata
=> Performance improvements in core library

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/utils/aio.py, libs/langgraph/poetry.lock, libs/langgraph/pyproject.toml, libs/langgraph/tests/test_pregel_async.py
- previous behavior was to buffer all output from subgraph until it finished, now subgraph steps are emitted as soon as produced, while the subgraph is still running
- this is slightly slower in benchmark scripts, but worth it as it's much "faster" in real-world latency
=> Stream subgraph output while it executes

libs/langgraph/tests/test_pregel_async.py
- we already have plenty of tests for this, but adding one more with a slight variation
=> Add one more unit test for exception propagation

libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/langgraph/pregel/types.py
This PR addresses two issues in the run_with_retry function:
* Exception Classes Misidentified as Callables:
Issue: Exception classes are callable, leading callable(retry_policy.retry_on) to mistakenly treat them as callables for custom retry logic.
* No Support for Lists in retry_on:
Issue: retry_on accepted only exception classes, tuples, or callables, not lists of exceptions (as defined in the documentation)
Summary of Changes:
* Modified retry_on type annotation to include List[Type[Exception]].
* Updated run_with_retry to handle lists and tuples when checking exceptions.
* Ensured exception classes are not incorrectly treated as callables.
* Added a TypeError if retry_on is of an unsupported type.
=> [Bug Fix] retry_on handling and add support for lists in RetryPolicy

docs/docs/how-tos/node-retries.ipynb
In the tutorial, added a code cell that briefly explains which exceptions the `default_retry_on` function retries on by default.
This information cannot be found in the tutorial or references, and can only be determined by examining the code directly.
This addition clarifies which exceptions will trigger a retry, helping users better understand the default retry behavior.
=> docs: Clarify default_retry_on retry behavior for exceptions

libs/sdk-py/langgraph_sdk/client.py
- after_seconds param to Runs.wait/stream/create
=> sdk: Add support for scheduled runs

libs/sdk-js/src/client.ts, libs/sdk-js/src/index.ts, libs/sdk-js/src/schema.ts, libs/sdk-py/langgraph_sdk/client.py, libs/sdk-py/langgraph_sdk/schema.py
- Lists all the versions for a given assistant
- Allows you to change assistant to point to specific version
=> sdk-py: add versioning for assistants

libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/managed/base.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
=> Remove runtime value substitution

libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py
- The thread running the event loop can block waiting for a coro to run, only background threads can
Closes #1800
=> Raise exception if sync method on async checkpointer is called from event loop thread

docs/docs/tutorials/introduction.ipynb
Encountered following error when running the example:
TypeError: can only concatenate list (not "tuple") to list
=> docs: fix quick start example code

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py
=> Use typing_extensions typeddict

libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py
=> checkpoint-postgres: handle null chars in metadata

.github/workflows/deploy_docs.yml
We'll need to add the same thing as part of CI testing, but a second check
during deployment wont hurt in case CI is by passed for whatever reason.
=> docs: Add linting check as part of docs deploy

libs/checkpoint-postgres/Makefile, libs/checkpoint-postgres/langgraph/store/postgres/aio.py, libs/checkpoint-postgres/langgraph/store/postgres/base.py, libs/checkpoint-postgres/tests/test_async_store.py, libs/checkpoint-postgres/tests/test_store.py
LTree supports too small a subset of labels (especially pre-postgres 16) and provides very little benefits over text columns (only improves less common namespace listing operations)
Rewrite to use a regular text column with a btree here.
=> Update PG Implementation

libs/scheduler-kafka/langgraph/scheduler/kafka/executor.py, libs/scheduler-kafka/langgraph/scheduler/kafka/orchestrator.py
- Some forks of aiokafka make this a required arg
=> scheduler-kafka: Pass loop arg to default async consumer and producer

libs/checkpoint/langgraph/checkpoint/base/__init__.py
In the Checkpointer Base schema definitions, the default value for the CheckpointNS column is an empty string: [link](https://github.com/langchain-ai/langgraph/blob/main/libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py#L40). 
However, in the ConfigurableFieldSpec, the default is None, which then makes model validation of configs hard, since the default is set to None which gets converted to NULL in postgres, and causes errors when trying to `aput` checkpoints into the database.
Specifically, like doing `model(**config).model_dump()` will turn `{'configurable': {'thread_id': '9517384e-1307-49bc-9456-158b8b8a003c'}` into like ` {'configurable': {'checkpoint_id': None, 'checkpoint_ns': None, 'thread_id': '9517384e-1307-49bc-9456-158b8b8a003c'}`)
This change fixes that by …
=> checkpoint: set CheckpointNS `ConfigurableFieldSpec` model default to empty string

libs/sdk-py/langgraph_sdk/client.py, libs/sdk-py/langgraph_sdk/schema.py
The response body of the endpoint `POST /threads/{thread_id}/state` looks like this:
```
{
"checkpoint": {
"thread_id": "e2496803-ecd5-4e0c-a779-3226296181c2",
"checkpoint_ns": "",
"checkpoint_id": "1ef4a9b8-e6fb-67b1-8001-abd5184439d1",
"checkpoint_map": {}
}
}
```
=> sdk-py: Update return type annotation for `Thread.update_state()` methods.

libs/sdk-py/langgraph_sdk/schema.py
The LangGraph API supports `custom` stream mode type.
Reference: https://github.com/langchain-ai/langgraph/blob/main/docs/docs/cloud/reference/api/openapi.json#L2403
=> sdk-py: Add `custom` stream mode to `StreamMode` type

libs/sdk-py/langgraph_sdk/client.py
The LangGraph API supports a list of `dict` for the `values` field for the `POST /threads/<thread_id>/state` endpoint.
Reference: https://github.com/langchain-ai/langgraph-api/blob/main/api/openapi.json#L3005-L3021
=> sdk-py: Add `Sequence[dict]` type to `values` param type for `update_state()`

libs/sdk-js/src/client.ts, libs/sdk-js/src/types.ts
- **fix(sdk-js): allow passing `checkpoint` when creating a run**
- **Remove error warning**
- **Remove deprecated message**
=> fix(sdk-js): pass checkpoint when creating run

libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- **fix(debug): add failing test for self-referencing**
- **fix(debug): address self-referencing**
=> fix(debug): self-referencing checkpoints when resuming streaming mid-thread

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/utils/config.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- **fix(debug): add failing tests**
- **Patch config before entering map_debug_checkpoint**
=> fix(debug): send checkpoint_map as well

libs/langgraph/langgraph/pregel/executor.py
- This could happen if a task happened to finish while the exit routine is running
Closes #2119
=> fix: Avoid errors from executor modifying tasks dict during exit routine

docs/docs/concepts/memory.md
When executing the code in the document about InMemoryStore, the following two errors occurred, so I fixed them.
> SyntaxError: positional argument follows keyword argument
> TypeError: BaseStore.get() missing 1 required positional argument: 'key'
=> Fix(docs): InMemoryStore example error

libs/langgraph/langgraph/pregel/remote.py
Assuming this wasn't intentional
=> fix: Fix typo in remote graph astream

.github/workflows/deploy_docs.yml
Reverts temporary change that was made yesterday to accommodate a link that was only available on the staging version of langchain.com
=> ci: update deploy docs workflow to check external links on langchain.com

libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- updates from inside Send tasks are applied in the order the Sends were created, if when you fan out, and have each task write results to a list with reducer, the final list is in the order you used when triggering
=> Test order of update application after Send

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- When calling get_state without a checkpoint id (ie to get the latest state) apply any pending writes for current checkpoint
=> lib: In calls to get_state apply pending writes

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- ie. tasks already executed should not show up in `next` list
=> lib: When getting latest state, alst make `next` reflect pending writes

libs/langgraph/langgraph/pregel/__init__.py
- This picks a default value for as_node which matches the node which last acted, even if the step didnt finish (due to an interrupt)
=> lib: When updating state from latest, apply pending writes first

libs/checkpoint/langgraph/checkpoint/base/__init__.py, libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/checkpoint/langgraph/checkpoint/serde/types.py, libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/errors.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/types.py, libs/langgraph/langgraph/utils/config.py, libs/langgraph/tests/__snapshots__/test_pregel.ambr, libs/langgraph/tests/__snapshots__/test_pregel_async.ambr, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/scheduler-kafka/tests/test_subgraph.py, libs/scheduler-kafka/tests/test_subgraph_sync.py
- This works similarly to the input() function from stdlib
- calling it in a node interrupts execution
- invoking the graph with Command(resume=...) will set ... as the return value of interrupt() so that the node can access the "answer" to the "question"
- This PR also starts the work to control the graph on invoke/stream with Command() input, to be continued in a future PR
```py
class State(TypedDict):
my_key: Annotated[str, operator.add]
market: str
async def tool_two_node(s: State) -> State:
if s["market"] == "DE":
answer = interrupt("Just because...")
else:
answer = " all good"
return {"my_key": answer}
tool_two_graph = StateGraph(State)
tool_two_graph.add_node("tool_two", tool_two_node)
tool_two_graph.add_edge(START, "tool_two")
tool_two = tool_two_graph.compile()
tool_two = …
```
=> lib: Add interrupt() function

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/tests/test_pregel.py
- update_state(None) copies checkpoint and keeps current (PUSH) tasks, eg for replay
- update_state(None, as_node=END) clears all tasks (PUSH or PULL)
=> lib: Restore prev behavior for update_state(None)

libs/langgraph/langgraph/pregel/utils.py
- if they both exist they're expected to share the same implementation, so looking in both is redundant
=> lib: find_subgraph doesn't need to look in both func and afunc

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/messages.py, libs/langgraph/langgraph/utils/config.py, libs/langgraph/tests/fake_chat.py
- This is asynchronous, so we shouldn't use for regular writes to the output stream (ie those from PregelLoop)
- For writes from subgraphs / nodes this is fine to use, as we make no guarantees about when those show up anyway
=> lib: For subgraphs / stream modes call stream.put as a callback in the original event loop

docs/docs/tutorials/langgraph-platform/local-server.md
`python-dotenv` not `python-dot-env`
=> docs: fix typo

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py
Replace hardcoded `PostgresSaver` with `cls` in the `from_conn_string` factory method to improve subclassing support.
- Modified `from_conn_string` to use `cls` instead of `PostgresSaver` when instantiating new instances
- This change allows subclasses to properly inherit and override the factory method
This refactor makes the `PostgresSaver` class more extensible by following Python's convention of using `cls` in class methods. This enables proper inheritance patterns where subclasses can reuse the factory method without modification.
The change is backward compatible and doesn't alter existing functionality. All existing tests should continue to pass.
=> fix: Replace hardcoded PostgresSaver with cls in factory method

libs/langgraph/langgraph/errors.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/prebuilt/tool_node.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/executor.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- This makes the command bubble up out of the current graph and be handled by the calling graph (the immediate parent)
- This could be extended to support eg. ROOT graph, or some other level
=> lib: Add Command(graph=Command.PARENT, ...)

libs/sdk-js/package.json, libs/sdk-js/src/client.ts, libs/sdk-js/src/utils/env.ts
Client can be used in non-Node environments, so we cannot assume `process.env` will succeed.
=> fix(js): Adds fallback for fetching environment variables

libs/checkpoint-postgres/langgraph/store/postgres/base.py, libs/checkpoint-postgres/tests/test_store.py
Adds a few of preliminaries:
1. Makes the returned "score" actually the result of the requested operation (cosine, inner_product, l2)
2. Sorts asc, etc. so that if you were to add an HNSW index (and not have any WHERE filters), it would be used
3. Drop the inner WHERE statement if no namespace or other filters are provided. See (2) for why.
I don't yet add an index to the migrations since I think we need to agree on the right balance to ensure it's actually used in common query patterns.
=> [postgres] Sort Ascending

docs/docs/tutorials/langgraph-platform/local-server.md
Small change to install the dependencies with `edit` mode so that users or freshman can see the effect immediately when they change the template code. As below,
`pip install -e .`
It's very good to evaluate how agent works and easy to test & re-develop!
=> docs: Use edit mode as default to install template

libs/langgraph/langgraph/graph/graph.py, libs/langgraph/tests/test_pregel.py
This allows building `StateGraph` where nodes are runnables returning `GraphCommand` (but don't have a notion of a return type hint), for example `ToolNode`
=> langgraph: relax graph validation to handle nodes without return typehints

libs/checkpoint-duckdb/langgraph/checkpoint/duckdb/__init__.py, libs/checkpoint-duckdb/langgraph/checkpoint/duckdb/aio.py, libs/checkpoint-duckdb/langgraph/store/duckdb/aio.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py, libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/aio.py
Replace hardcoded database saver class names with `cls` in `from_conn_string` factory methods to improve subclassing support
* Replaced direct class instantiations with `cls(conn)` in `from_conn_string` classmethods across all database implementations
* Updated both synchronous and asynchronous variants for DuckDB, PostgreSQL, and SQLite savers
This refactor makes the database saver classes more extensible by following Python's convention of using `cls` in class methods. This enables proper inheritance patterns where subclasses can reuse the factory methods without needing to override them. Previously, the hardcoded class names would always instantiate the parent class, even when called from a subclass.
The change is backward compatible and doesn't alter existing functionality. All …
=> fix: make database saver classes inheritance-friendly

libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/scheduler-kafka/tests/any.py, libs/scheduler-kafka/tests/test_subgraph.py, libs/scheduler-kafka/tests/test_subgraph_sync.py
- Includes support for interrupt loops
=> lib: Add support for multiple interrupts per node

libs/langgraph/langgraph/graph/__init__.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/scheduler-kafka/tests/test_push.py, libs/scheduler-kafka/tests/test_push_sync.py, libs/sdk-py/langgraph_sdk/schema.py
- Now we have only Command
- Command(goto=) combines the previous functionality of Command(send=) and GraphCommand(goto=)
=> lib: Merge GraphCommand and Command

libs/checkpoint/langgraph/checkpoint/memory/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/utils/runnable.py, libs/langgraph/tests/test_pregel.py
- don't create contextvars.Context/asyncio.Task in RunnableSeq (not needed as each step creates it if necessary)
- don't run in-memory-saver methods in background threads (no point as they hold the gil)
- avoid calling should_interrupt when no interrupts set
=> lib: Performance improvements

docs/docs/concepts/persistence.md
Hi,
I was reading the [persistence](https://langchain-ai.github.io/langgraph/concepts/persistence/#update-state) concept in LangGraph and found a sentence with a missing verb, so I fixed it.
=> Fixed the documentation for the persistence concept

docs/docs/how-tos/update-state-from-tools.ipynb
Hi,
While reading the [update state from tools](https://langchain-ai.github.io/langgraph/how-tos/update-state-from-tools/) tutorial. I noticed that this code snippet contains a syntax error:
```python
def call_tools(state):
...
commands = [tools_by_name[call["name"].invoke(call, config={"coerce_tool_content": False}) for tool_call in tool_calls]
return commands
```
There is a missing closing bracket `]` in the list comprehension. Additionally, the variable `call` inside the list comprehension is undefined, it should be `tool_call`.
Here is a corrected version of the code:
```python
def call_tools(state):
...
commands = [tools_by_name[tool_call["name"]].invoke(tool_call, config={"coerce_tool_content": False}) for tool_call in tool_calls]
return commands
```
=> Fixed the code snippet in the Update State From Tools tutorial

libs/cli/langgraph_cli/cli.py, libs/cli/langgraph_cli/config.py, libs/cli/poetry.lock, libs/cli/pyproject.toml, libs/cli/tests/unit_tests/test_config.py
And inject in dockerfile if presented
=> [CLI] Add auth param to langgraph.json

docs/docs/how-tos/tool-calling.ipynb
Automatically leads to the correct `ToolNode` section instead of the top
=> docs: Update correct ID for initial ToolNode hyperlink

docs/docs/how-tos/multi-agent-multi-turn-convo.ipynb
there were two same import
"from langchain_openai import ChatOpenAI"
=> docs: removed redundant import from the example

docs/docs/cloud/deployment/cloud.md
Clarifying that in order to install the `hosted-langserve` GitHub app, the GitHub user must be an owner of the organization or account.
=> docs(cloud): Add note about GitHub org/acc owner

libs/cli/poetry.lock, libs/cli/pyproject.toml
When installing 'inmem' variant.
This will ensure you get the required updates for auth.
=> [CLI] Bump min-bound for langgraph-api

docs/docs/concepts/agentic_concepts.md
Made some of the explanations more clear by rephrasing certain parts of the sentence.
Fixed minor grammar mistakes also.
=> docs: Improve explanation and fix grammar mistakes in agentic concepts guide

docs/_scripts/notebook_hooks.py
=> docs: Add highlight-next-line

docs/_scripts/generate_api_reference_links.py, docs/_scripts/notebook_convert.py, docs/_scripts/notebook_hooks.py
Generate api references from any markdown -- this will handle markdown files in notebooks as well as code blocks in plain markdown
=> docs: improve api reference generation in code blocks

libs/sdk-js/package.json, libs/sdk-js/src/types.ts, libs/sdk-py/langgraph_sdk/schema.py, libs/sdk-py/pyproject.toml
Align typing with JS:
https://github.com/langchain-ai/langgraphjs/blob/main/libs/langgraph/src/constants.ts#L226
=> fix(sdk): Fix SDK Command.update type

libs/langgraph/langgraph/func/__init__.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
Also add support for just `@task` without the ()'s
=> Support multiple args in @task's

libs/langgraph/README.md, libs/langgraph/bench/fanout_to_subgraph.py, libs/langgraph/langgraph/graph/message.py, libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/langgraph/prebuilt/tool_node.py, libs/langgraph/langgraph/prebuilt/tool_validator.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/types.py, libs/langgraph/pyproject.toml, libs/langgraph/tests/test_interruption.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_large_cases_async.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/langgraph/tests/test_tracing_interops.py, libs/langgraph/tests/test_utils.py
Within `libs/langgraph`, change all `TypedDict` imports to come from `typing_extensions` rather than `typing`, as `pydantic` doesn't like the latter.
Additionally, add a ruff rule to ban these imports too (so this doesn't regress).
Solves  #2909.
=> Import `TypedDict` from `typing_extensions`, add ruff rule

README.md, libs/langgraph/README.md
When looking at [docs](https://langchain-ai.github.io/langgraph/) this sentence is confusing, not clear there's two separate links or why one of them would lead to repo
=> docs: readme nit

libs/sdk-py/langgraph_sdk/auth/types.py, libs/sdk-py/pyproject.toml
Share "namespace" to simplify handler def on a resource level
=> Unify type-naming of search param

docs/docs/how-tos/deploy-self-hosted.md
@langchain-infra, is this correct? Is this needed or is it redundant/unnecessary?
=> docs: Add docs for `LANGCHAIN_ENDPOINT` for self-hosted deployments

docs/docs/concepts/deployment_options.md, docs/docs/concepts/self_hosted.md
=> docs: Add note about LangGraph Platform UI not available for self-hosted deployments

libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_state.py
=> langgraph: fix ismethod check in add_node

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py
```python
agent = create_react_agent("anthropic:claude-3-5-sonnet-latest", [add])
agent.invoke({"messages": [("user", "what's 3 + 5")]})
```
=> langgraph: allow model names as strings in create_react_agent

docs/docs/concepts/langgraph_studio.md
=> docs: Update Studio FAQ

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/poetry.lock, libs/langgraph/pyproject.toml, libs/langgraph/tests/test_algo.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_pregel_async.py
- order was incorrectly based on task id, instead of the correct task path
- this requires storing task paths on checkpointers
- addition of task_path to put_writes is made backwards compatible by checking signature on call, and treating it as an optional arg
=> Fix Send order after interrupt/resume

libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/scheduler-kafka/tests/test_subgraph.py, libs/scheduler-kafka/tests/test_subgraph_sync.py
- Also stop exposing writes in config, in favor of scratchpad
=> Fix unexpected re-use of null resume value by subgraphs

docs/mkdocs.yml
Currently, if you're viewing a how-to guide and you click "How-to Guides" in the sidebar, you aren't navigated back to the index page (it will work if you click on a different guides section). To get back to the index page, you need to scroll up and click the breadcrumbs.
After this change, clicking the link in the sidebar should navigate you to the index page regardless of the page you are viewing.
Only side-effect from what I can tell is that "Home > Introduction" just becomes "**Home**", which I think is fine (maybe preferable).
Before:
After:
=> docs[patch]: enable navigation back to index pages from child pages via sidebar

docs/mkdocs.yml
The API reference is marked as experimental right now, so this is OK to expose to make it easier to share w/ beta users.
=> docs: expose functional api reference

libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/utils/future.py, libs/langgraph/tests/test_pregel_async.py
- both issues are related to the fact that waiters for futures are notified of completion before "done" callbacks are called
- 1st issue manifested as interrupt stream event being emitted before the result of a task that logically finished first (it's in the line above in body of the entrypoint function) -> this is solved by always returning to use code a fresh future chained on the original future, because chaining is done via done callbacks (therefore the chained future will only resolve after done callbacks of the original feature are called)
- 2nd issue mainfested as sometimes (very rarely) the last stream event not being printed before stream() finishes. this is solved by ensuring we only return out of PregelRunner.tick() once all "done" callbacks are called, previously we were …
=> Fix two issues with task/stream timing

libs/langgraph/langgraph/prebuilt/chat_agent_executor.py, libs/langgraph/pyproject.toml
So that you can call agent.nodes['agent'].invoke({'messages': []}) without needing to specify is_last_step. very helpful for evaluating just the model node of the agent
=> python[patch]: call create_react_agent model node without is_last_step

docs/docs/how-tos/persistence_postgres.ipynb
Fixed a typo that was interrupting the markdown.
=> Update persistence_postgres.ipynb to remove typo in markdown cell.

docs/docs/tutorials/langgraph-platform/local-server.md
Small typo in the Local Server page: https://langchain-ai.github.io/langgraph/tutorials/langgraph-platform/local-server/
=> DOCS: Incorrect reference to JS/TS SDK as Python SDK

libs/langgraph/langgraph/func/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/call.py, libs/langgraph/langgraph/utils/runnable.py, libs/langgraph/tests/test_pregel_async.py
- now using same logic as in langsmith sdk, treating as single args dict, based on function signature
=> Fix tracing of args for @task decorated functions

libs/langgraph/langgraph/pregel/executor.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/utils/future.py, libs/langgraph/tests/test_pregel_async.py
- When using an async entrypoint you can now freely mix and match sync and async tasks with a uniform api (ie all tasks return a sync or async future depending on context)
- Fix issues with scheduling deeply nested tasks (use threadsafe methods to schedule coroutines and create futures)
=> Re-enable support for running sync tasks from async entrypoints

libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/tests/test_large_cases.py
- this was not possible in async where all done callbacks are called in next tick
- in sync case this would manifest as the first task done callback seeing counter == 1 and thus setting event
- the fix is to unset the event whenever a task is scheduled
=> Fix timing issue where a sync task would finish before the other one was registered in futures dict

libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- async tests are placed in test_pregel_async, not in test_pregel
- to avoid tests placed in wrong file being accidentally skipped i've added the auto-async mark to sync test file
=> Enable async tests that were being skipped

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/scheduler-kafka/tests/test_subgraph.py, libs/scheduler-kafka/tests/test_subgraph_sync.py
- Same solution as used in python stdlib to name threads and asyncio tasks
=> Make scratchpad counters thread-safe

libs/langgraph/langgraph/func/__init__.py, libs/langgraph/langgraph/pregel/call.py, libs/langgraph/tests/test_pregel_async.py
- note this type is never instantiated, it is only used for typing (we cannot make it a protocol as it inherits from concurrent.futures.Future)
=> Improve typings for task, it now returns a mixed sync/async future protocol

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/pregel/utils.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py
- The result of these doesnt change once a node is created, and it's fairly expensive to run, so great thing to cache
- There's a variety of errors that can come from inspecting the source code of a function (part of what this does) so adding a catch-all try-except block as this should be best-effort, not crash your graph
=> Guard and cache calls to find_subgraph_pregel

libs/sdk-js/src/client.ts, libs/sdk-js/src/schema.ts
Allow assigning `threadState?.checkpoint` to the `configurable` object without TSC throwing "Index signature for type 'string' is missing in type".
=> fix(sdk-js): use `type` instead of `interface` to avoid TS errors

libs/sdk-js/src/client.ts, libs/sdk-js/src/index.ts, libs/sdk-js/src/types.messages.ts, libs/sdk-js/src/types.stream.ts, libs/sdk-js/src/types.ts, libs/sdk-js/src/utils/async_caller.ts
StateType, UpdateType is set on the Client rather than on `RunsClient.stream` because of lack of partial type arguments application. 
This PR also describes the message serialization format emitted by LangGraph Server (which may change ie. converting `type` to `role`). Avoiding direct import of `@langchain/core` for the core LangGraph SDK client, thus these types were copied from `@langchain/core` (a script is used to aid with keeping track with core)
=> feat(sdk-js): strongly-typed messages, state/update-type, stream mode

docs/_scripts/add_translation.py
A script to add typescript translations. We can improve by automatically adding markdown tabs appropriately and parallelizing the llm calls
=> docs: add script to add typescript translations

docs/docs/concepts/low_level.md
Add within to better explain moving from one subgraph to another
=> docs: fix grammatical error for navigating node to parent section

docs/_scripts/notebook_convert.py, docs/_scripts/notebook_convert_templates/md_executable/index.md.j2, docs/tests/unit_tests/test_notebook_conversion.py
* Add ast parsing to determine whether we should include result="ansi". It's not meant to be perfect, but will hopefully catch the most common cases. Still requires manual review.
* Ideally we could suppress output in markdown-exec in the future.
=> docs: add check code output for result="ansi"

libs/langgraph/langgraph/pregel/remote.py
Currently when using RemoteGraph the recursion_limit cannot be set, due to the sanitize_config.
=> Ensure remote respects recursion_limit param if it's passed

libs/langgraph/langgraph/pregel/__init__.py
Remove incorrect example from Pregel class. Will follow later this week with better docs
=> reference: remove incorrect example from pregel class

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/checkpoint/pyproject.toml
- Packer instances can't be kept in memory as they retain memory after used
=> checkpoint: Fix memory leak in checkpoint serializer

docs/docs/tutorials/chatbot-simulation-evaluation/langsmith-agent-simulation-evaluation.ipynb, docs/docs/tutorials/chatbot-simulation-evaluation/simulation_utils.py
While following the LangChain tutorial on [chatbot simulation evaluation](https://langchain-ai.github.io/langgraph/tutorials/chatbot-simulation-evaluation/langsmith-agent-simulation-evaluation/), I encountered some issues and made the following fixes to ensure proper functionality:
1. Updated deprecated `run_on_dataset` to `evaluate` to resolve PydanticUserError
- Following the migration guide: https://docs.smith.langchain.com/old/evaluation/migration
2. Added missing `langchain_community` import
3. Added required `simulation_utils.py` file to docs directory
- Source: https://github.com/langchain-ai/langgraph/blob/main/examples/chatbot-simulation-evaluation/simulation_utils.py
Successfully ran the `langsmith-agent-simulation-evaluation.ipynb` notebook without any errors.
=> Fix issues in chatbot simulation evaluation tutorial

docs/docs/concepts/low_level.md
Update `low_level.md`: Add a tutorial link for map-reduce, now it's perfect !!!
=> docs(concepts) : Add a tutorial link for map-reduce

docs/docs/concepts/langgraph_studio.md
messed up an indentation that was causing the warning to not render correctly
=> docs: fix deprecation warning style

libs/langgraph/langgraph/pregel/loop.py
- Ignore input if being passed in when a checkpoint already exists for that run_id
=> When retrying a previously attempted run, resume from previous checkpoint

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/langgraph/tests/__snapshots__/test_pregel.ambr, libs/langgraph/tests/test_pregel.py
- when the class can't be found, or can't be constructed, fallback to returning the kwargs dict, instead of returning nothing
=> When rehydrating a pydantic module, fallback to returning the kwargs dict

libs/langgraph/langgraph/func/__init__.py
An async function of the form `def foo(P) -> T` has type `Callable[[P], Awaitable[T]]`. The old type annotations then converted the function into a `Callable[[P], SyncAsyncFuture[Awaitable[T]]]` which is incorrect.
The change introduced in this commit updates the type annotations to ensure the `Awaitable[T]` is correctly unwrapped.
I've tested it locally and confirmed it work on:
```python
@task 
def sync_fn(a: int) -> int: ...
@task 
def async_fn(a: int) -> int: ...
```
Let me know if you want me to add tests, just let me know how you test type annotations.
=> chore(langgraph): fix typing of task decorator

libs/sdk-js/src/react/stream.tsx
We still need intermediate messages to ensure the client state and server state is in-sync as quickly as possible.
=> fix(sdk-js): stream intermediate values with messages-tuple

libs/checkpoint/langgraph/store/base/__init__.py
=> Item `updated_at` not being correctly initialized with the correct attribute.

README.md, libs/langgraph/README.md
Currently the version badge showing langgraph version as PyPi shield image is linking to the shield image. It would be more intuitive to link it to PyPi.
=> docs: Fix version badge by linking it to PyPi instead of shield

libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py
- When a pydantic input schema isued but dict input is passed in validate it once after running hidden START node. If the input is an instance of the input model we skip validation altogether
- When entering each node we need to create a standalone instance of the state class, but we can now skip validation, as it's now run once elsewhere
=> Avoid validating pydantic state models when we can

docs/docs/concepts/persistence.md
This PR fixes the type of `foo` in the `State` class in Persistence documentation. The type was previously defined as `int`, but the code uses it as a `str`.
Updated the type of `foo` in the documentation to `str` to match its actual usage in the code.
No changes to the functionality or codebase, only a documentation fix.
=> docs: fix state type in Persistence documentation

.github/workflows/deploy_docs.yml, docs/Makefile, docs/_scripts/third_party_page/get_download_stats.py
At some point, we can run on a cron schedule
=> ci: limit downloads from pypi stats to main branch

libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/pregel/write.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- remove usage of require_at_least_one_of, we shouldn't be enforcing presence of keys in inputs/updates, an empty dict is a valid input/update
- ensure that values that were explcitly set/assigned in pydantic model are saved even if equal to default value
=> Update handling of updates/inputs passed in as pydantic models

libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/tests/test_pregel_async.py
- When multiple parallel tasks and/or subgraphs emit interrupts some were missing from stream output
=> Fix missing interrupts in stream

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_pregel.py
- Previously the global resume value was passed to subgraphs without being consumed
- This would result in two parallel subgraph calls being able to use the same resume value
- Note this behavior can't be implemented over the wire, that will be fixed in future PR
Closes #3398
=> When using global resume value, ensure subgraphs consume it

docs/docs/how-tos/command.ipynb
- fix typo / add missing word
- make sentence relating to how to navigate between sub graphs clearer in the docs
=> docs: make sentence relating to how to navigate between sub graphs clearer in the docs

libs/langgraph/langgraph/channels/any_value.py, libs/langgraph/langgraph/channels/base.py, libs/langgraph/langgraph/channels/binop.py, libs/langgraph/langgraph/channels/dynamic_barrier_value.py, libs/langgraph/langgraph/channels/ephemeral_value.py, libs/langgraph/langgraph/channels/last_value.py, libs/langgraph/langgraph/channels/named_barrier_value.py, libs/langgraph/langgraph/channels/topic.py, libs/langgraph/langgraph/channels/untracked_value.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/io.py
- Using a sentinel value is faster than raising-catching an exception
=> Speed up task triggers check

libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/io.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_large_cases_async.py
- Was O(n^2) due to individual channels created for every conditional edge, including the default cond edge created for Command
- Now using a single channel per node for all conditional edge / command triggers, reducing to linear complexity
- Improves run time on sequential(200) from 1.8s to 0.14s
=> Improve prepare_single_task trigger checks to linear complexity

libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py
* Document that `check_same_thread` as an option when creating sqlite connection.
* Document why it's OK to do that.
=> Improve documentation string for SqliteSaver

docs/docs/cloud/deployment/setup_pyproject.md
LangGraph officially supported Python 3.13 back in October 2024: 
https://changelog.langchain.com/announcements/langgraph-is-now-compatible-with-python-3-13
But why suggest restricting the version of Python at all? The app/agent owner will be in control of the runtime version anyway, so don't add unnecessary restrictions.
Note this example from Poetry: https://python-poetry.org/docs/pyproject/#requires-python
I did not refactor pyproject.toml to the newer Poetry 2 / uv format, but I can do that in a future PR if it will help... please don't let that block approval+merging this PR.
=> doc: remove Python max version limit from example pyproject.toml

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/loop.py
- When there are no values in checkpoint no need to run through all the PULL candidates
- When there are input writes save updated_channels to use on the next call to prepare_next_tasks
=> Use fast path for prepare_next_tasks on input

libs/checkpoint/langgraph/checkpoint/memory/__init__.py, libs/checkpoint/tests/test_memory.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/memory_assert.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- This makes our checkpoint benchmarks more closely resemble the behavior of our prod checkpointers
- Also found and fixed a bug w multiple subgraphs in same node accidentally sharing checkpoints
=> Use incremental storage in memory checkpointer

docs/docs/tutorials/storm/storm.ipynb
- Added a validator to sanitize 'name' fields and prevent string_pattern_mismatch errors.
- Replaced deprecated `dict` method with `model_dump` in line with Pydantic v2.0 migration guidelines.
- Updated gen_perspectives_chain and gen_queries_chain to ensure compatibility with structured output and include raw data where needed. This allows use of fast_llm across the notebook.
=> fix(docs): Update deprecated methods and add validator

docs/docs/concepts/pregel.md
I noticed a very minor issue in the formatting of the Concepts > Pregel doc: (https://langchain-ai.github.io/langgraph/concepts/pregel/#high-level-api) (https://github.com/langchain-ai/langgraph/blob/main/docs/docs/concepts/pregel.md)
You can see in the image below that there is a python codeblock, then a pycon block, and inside that block there is an extra triple-backtick/code fence, and then text at the bottom, which it appears like it is supposed to be a separate python block, like the one above it. I.e., clearly:
```
```python
print(graph.channels)
```
is intended to be:
```python
print(graph.channels)
```
I'm pretty sure this is due to an extra whitespace character before the preceding closing code fence, which is throwing off the formatting.
My VS-Code/extensions can't really render …
```
=> docs(pregel): One-line markdown formatting quick-fix

libs/langgraph/bench/__main__.py
Remove some benchmarks temporarily so we can fit more stuff into the annotation
=> benchmark: remove some benchmarks

libs/langgraph/langgraph/channels/topic.py
This PR fixes the return type annotation of the `update` method from `None` to `bool`, as the method returns a boolean value indicating whether self.values has changed
=> patch: fix return type of Topic.update

libs/langgraph/langgraph/graph/state.py
Fixes https://github.com/langchain-ai/langgraph/issues/4051
=> langgraph: use correct type for node destination annotations

libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/types.py
- make scratchpad class frozen now that its members are never reassigned
- replace next(gen expr) with for-loop to avoid allocating generator objects
=> Reduce perf impact of pregel scratchpad creation

libs/checkpoint/langgraph/checkpoint/serde/jsonplus.py, libs/langgraph/langgraph/channels/any_value.py, libs/langgraph/langgraph/channels/base.py, libs/langgraph/langgraph/channels/binop.py, libs/langgraph/langgraph/channels/dynamic_barrier_value.py, libs/langgraph/langgraph/channels/ephemeral_value.py, libs/langgraph/langgraph/channels/last_value.py, libs/langgraph/langgraph/channels/named_barrier_value.py, libs/langgraph/langgraph/channels/topic.py, libs/langgraph/langgraph/channels/untracked_value.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/manager.py, libs/langgraph/langgraph/utils/future.py, libs/langgraph/tests/test_channels.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- If the value to serialize is None we can use encode it in the string type, and skip msgpack encoding
- Use None value for edge/branch channels in StateGraph
=> Add fast path to serialize None values

libs/checkpoint/langgraph/checkpoint/base/__init__.py, libs/langgraph/bench/sequential.py, libs/langgraph/langgraph/channels/any_value.py, libs/langgraph/langgraph/channels/base.py, libs/langgraph/langgraph/channels/binop.py, libs/langgraph/langgraph/channels/ephemeral_value.py, libs/langgraph/langgraph/channels/last_value.py, libs/langgraph/langgraph/channels/untracked_value.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/checkpoint.py, libs/langgraph/langgraph/pregel/loop.py
- This mirrors the work done earlier on BaseChannel.get()
- Comparing to a sentinel value is significantly faster than raising and catching an exception
=> Avoid raise-catch strategy in BaseChannel.checkpoint()

libs/checkpoint/langgraph/checkpoint/base/__init__.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/checkpoint.py, libs/langgraph/langgraph/pregel/loop.py
- This should be controlled by the langgraph version, not the version of langgraph-checkpoint installed
=> Maintain checkpoint LATEST_VERSION constant in langgraph lib

docs/docs/concepts/functional_api.md
Import `MemorySaver` for the code to run without expanding the example
=> docs: add missing MemorySaver import for unexpanded example

libs/cli/langgraph_cli/config.py, libs/cli/tests/unit_tests/cli/test_cli.py
Allow the CLI to work with dict format for the graph specification.
```json
{
"dependencies": ["./my_agent"],
"graphs": {
"agent": {
"path": "./my_agent/agent.py:graph",
"description": "this is my agent description"
}
},
"env": ".env"
}
```
And backwards compatible with:
```json
{
"dependencies": ["./my_agent"],
"graphs": {
"agent": "./my_agent/agent.py:graph",
},
"env": ".env"
}
```
=> cli: support dict format for graph specification in langgraph.json

libs/langgraph/bench/__main__.py, libs/langgraph/langgraph/constants.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_interruption.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- This provides a new mode of execution where only the last checkpoint is saved
- We save the last checkpoint no matter how the agent run is terminated (success, error, interrupt, etc)
- This cuts down on cpu time spent on checkpointing, while not losing any resilience benefits, given individual task writes are still saved
- If an error occurs and the run is retried, any tasks that completed successfully before will be skipped (as currently)
- checkpoint_during=True is useful when you want to time-travel to inner steps of a run
- The default value will remain the current behavior, ie. checkpoint_during=True
=> Add checkpoint_during arg

libs/langgraph/langgraph/func/__init__.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/algo.py, libs/langgraph/langgraph/pregel/call.py, libs/langgraph/langgraph/pregel/read.py, libs/langgraph/langgraph/pregel/retry.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_retry.py
* support passing `retry=(RetryPolicy(...), RetryPolicy())`
* fix bugs with `default_retry_on` and backoff calculation
* add tests
=> langgraph: allow passing a list of retry policies

docs/docs/cloud/deployment/cloud.md, docs/docs/cloud/deployment/self_hosted_control_plane.md, docs/docs/cloud/deployment/self_hosted_data_plane.md, docs/docs/concepts/deployment_options.md, docs/docs/concepts/langgraph_cloud.md, docs/docs/concepts/langgraph_self_hosted_control_plane.md, docs/docs/concepts/langgraph_self_hosted_data_plane.md, docs/docs/tutorials/deployment.md
=> docs: Add alpha and beta labels for respective LangGraph Platform deployment options

libs/sdk-py/langgraph_sdk/schema.py
Unsure if this is related to a recent user misconception about `checkpoint_ns`' role, but in any case would like to make all docstrings as unambiguous as possible.
=> Make docstring even less ambiguous

docs/docs/concepts/langgraph_cli.md
Correct a typo in documentation: 'thedocker' changed to 'the docker'
=> fix(docs): fix typo

libs/checkpoint-postgres/langgraph/store/postgres/base.py
=> bug: use "fields" instead of "text_fields" in _ensure_index_config

libs/checkpoint-postgres/langgraph/store/postgres/base.py, libs/checkpoint-postgres/pyproject.toml, libs/checkpoint-postgres/tests/test_async_store.py, libs/checkpoint-postgres/tests/test_store.py
The configuration expects the key "fields", not "text_fields": I had failed to update across all implementations in the original PR
=> Fix text fields naming

libs/cli/langgraph_cli/cli.py, libs/cli/langgraph_cli/config.py, libs/cli/langgraph_cli/docker.py, libs/cli/pyproject.toml, libs/cli/tests/unit_tests/cli/test_cli.py
Using this argument, you can get more customization since you can do `langgraph build` or directly `docker build` your image and then re-use the `langgraph up --image my-image` and have it also spin up redis & postgres for you.
Easier then writing your own compose file
=> Add image arg to up command

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/test_react_agent.py
Removes support for `state_modifier` param in `create_react_agent`. To specify system prompt / instructions use `prompt` parameter.
=> prebuilt: remove state_modifier

docs/docs/how-tos/auth/custom_auth.md
Should be `defaultHeaders`: https://github.com/langchain-ai/langgraph/blob/main/libs/sdk-js/src/client.ts#L76
=> docs: Fix JS example in custom auth how-tos

docs/mkdocs.yml
The `Local deploy` page's left-hand navigation looks like this:
=> docs: Fix broken navigation for `Local deploy` page

docs/docs/cloud/concepts/streaming.md, docs/docs/concepts/streaming.md, docs/mkdocs.yml
* Split streaming concepts between OSS and langgraph platform
* LangGraph platform streaming requires more work
=> docs: re-organize streaming concepts

docs/docs/agents/memory.md
I was having trouble following this section of the docs and I realized it is because the incorrect tools is included in the tools list. `update_user_info` was defined earlier in the file but never used.
=> docs: Fixed incorrect tool in 'Write from tools' documentation

libs/langgraph/tests/conftest.py, libs/langgraph/tests/conftest_store.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Use a single fixture that returns the store, instead of list of names
=> More idiomatic sync/async store fixtures in pytest

docs/docs/concepts/auth.md, docs/docs/concepts/deployment_options.md, docs/docs/concepts/langgraph_standalone_container.md, docs/docs/concepts/plans.md, docs/docs/troubleshooting/errors/INVALID_LICENSE.md, docs/docs/tutorials/deployment.md
Self-Hosted Lite is a server version, not a deployment option.
=> docs: Remove self-hosted lite deployment option

docs/docs/concepts/server-mcp.md
Example to connect to the MCP server of a deployed graph in langgraph platform (langchain-mcp-adapters).
The graph can be used as a MCP tool.
=> docs: mcp adapters example for deployed graph

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/tests/test_remote_graph.py, libs/scheduler-kafka/langgraph/scheduler/kafka/executor.py
- remove match_cached_writes from PregelRunner args (now called by PregelLoop internally)
- this will be helpful when implementing distributed runner classes
=> Improve how we match cached writes for async imperative tasks

docs/docs/tutorials/langgraph-platform/local-server.md
Docs have the wrong npx command to install LangGraph CLI:
`npx @langchain/langgraph-cl` instead of `npx @langchain/langgraph-cli`
=> docs: typo in npx command to install LangGraph CLI

docs/docs/concepts/pregel.md, libs/langgraph/langgraph/pregel/__init__.py
Hi,
I have spotted a typo in the reducer examples of pregel graph, part "BinaryOperatorAggregate"
previous example code: 
```python
def reducer(current, update):
if current:
return current + " | " + "update"
else:
return update
```
corrected version
```python
def reducer(current, update):
if current:
return current + " | " + update
else:
return update
```
=> docs: fix example pregel reducer

docs/docs/agents/tools.md, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py
Patch to support llm provider hosted tools (server tools) in `create_react_agent`, like:
```py
from langgraph.prebuilt import create_react_agent
def add(a: int, b: int):
"""Add two numbers"""
return a + b
web_search = {
"type": "web_search_preview"
}
agent = create_react_agent(
model="openai:gpt-4.1",
tools=[add, web_search]
)
search_result = agent.invoke({
"messages": [{"role": "user", "content": "what's the weather in nyc today?"}]
})
math_result = agent.invoke({
"messages": [{"role": "user", "content": "what's 42 + 7?"}]
})
web_search = {
"type": "web_search_20250305",
"name": "web_search",
"max_uses": 3
}
agent = create_react_agent(
model="anthropic:claude-3-5-sonnet-latest",
tools=[add, web_search]
)
search_result = agent.invoke({
"messages": [{"role": "user", "content": "what's the …
```
=> prebuilt: support provider builtin tools in `create_react_agent`

docs/docs/concepts/langgraph_control_plane.md
1. Once a deployment is created, the deployment type (`Development` , `Production`) cannot be changed.
2. Added a few details about database provisioning.
=> docs: Add warning about immutable deployment types

libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- These exceptions should not be re-raised at end of tick, given they're handled explicitly by the developer in their entrypoint
Closes #4294
=> Fix exception handling for imperative tasks

libs/langgraph/langgraph/pregel/io.py, libs/langgraph/tests/test_pregel_async.py
- This is only used by astream_events, which is a langchain core code path we no longer recommend
- No documented langgraph code relies on this, so prefer to remove
=> Remove dict subclasses used for values/updates stream chunks

.gitignore, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/protocol.py, libs/langgraph/langgraph/typing.py, libs/langgraph/tests/test_state.py, libs/langgraph/tests/test_type_checking.py
* Type checking on input for `invoke`, `stream`, etc matches that of either `InputT` or `StateT`, depending on if `InputT` is specified
* Type checking on node signatures, requiring `state` to be typed as `StateT`
* Ensuring the type used for `state_schema` is a typed dict spec, dataclass, or base model type
```py
from typing import Annotated, Any
from langgraph.checkpoint.memory import InMemorySaver
from typing_extensions import TypedDict
from langgraph.graph import StateGraph
from operator import add
class State(TypedDict):
info: Annotated[list[str], add]
graph_builder = StateGraph(State)
def start(state: State) -> Any:
return {"info": state["info"] + ["!"]}
def invalid_node() -> Any: ...
graph_builder.add_node("start", start)
graph_builder.add_node("invalid", invalid_node, input=State) …
```
=> Improve type checking on graph `init` and `invoke`/`stream`

libs/langgraph/langgraph/graph/state.py
- We no longer auto create a same-name channel for each node, so this limitation can now be lifted
=> Allow same-name channels and nodes in StateGraph

libs/langgraph/langgraph/pregel/runner.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- We should not re-raise exceptions in commit() as that is now called in a future done callback
- panic_or_proceed takes care of re-raising exceptions as needed anyway
=> Fix step_timeout causing ParentCommand/GraphInterrupt exception to bubble up

.github/workflows/deploy_docs.yml
This is just temporary while we have changes for `v1` on the `main` branch.
=> docs: deploy from v0 branch for now

libs/cli/langgraph_cli/cli.py, libs/cli/tests/unit_tests/cli/test_cli.py
A given `langgraph.json` with more than one `dependencies`:
```
{
"python_version": "3.12",
"dependencies": [
".",
"../../libs/proto",
"../../libs/common"
],
...
}
```
Will produce a docker build command:
`docker build --build-context proto=abs_path,common=abs_path`
which is not valid. It is not possible to separate the different --build-context using a comma. Rather the following command should be generated:
`docker build --build-context proto=abs_path --build-context common=abs_path`
I am using the latest `Docker version 28.2.2, build e6534b4` but I don't believe it ever worked.
=> 🐛 [CLI] Generate one `--build-context` argument for each dependency in the `docker build` command.

docs/docs/cloud/reference/cli.md
=> docs: add docs for image_distro cli option

docs/docs/concepts/low_level.md, docs/docs/concepts/server-mcp.md, docs/docs/how-tos/graph-api.ipynb, libs/langgraph/bench/fanout_to_subgraph.py, libs/langgraph/langgraph/_typing.py, libs/langgraph/langgraph/func/__init__.py, libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/protocol.py, libs/langgraph/tests/test_deprecation.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/langgraph/tests/test_state.py, libs/langgraph/tests/test_type_checking.py, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py
* rename `input` -> `input_schema`
* rename `output` -> `output_schema`
* make graphs generic on `OutputT` to prep for future type checking
All renaming operations are backwards compatible in that we populate old input / output into their respective new schemas!
=> deprecate `input` and `output` in favor of `input_schema` and `output_schema`

docs/docs/tutorials/get-started/1-build-basic-chatbot.md
The current [Build a basic chatbot](https://langchain-ai.github.io/langgraph/tutorials/get-started/1-build-basic-chatbot/) tutorial shows a graph diagram that includes both a `START` and an `END` node. However, the tutorial does not define or mention the END node at all, which may cause confusion.
Running the code as-is from the current version of this tutorial does not produce a graph matching the image shown in the tutorial.
This PR adds documentation and code for adding the `END` node as well. The alternative was to update the image, but it might be more valuable to show users how to add an exit point explicitly.
=> docs: Update `1-build-basic-chatbot.md` to add a section about `END` node

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py
I am working on creating a checkpointer for the oracle database and am referring to the postgres checkpointer.
I noticed that `get_tuple` and `list` (and also `aget_tuple` and `alist`) generate `CheckpointTuple`, but the code is duplicated.
In this PR, a new method to generate `CheckpointTuple` is created and reused.
The original implementation of `get_tuple`(`aget_tuple`) does not read the `thread_id` and `checkpoint_ns` from the `value`, but even if they were read from the `value`, the overhead would be negligible and the code duplication elimination would be more beneficial.
=> Centralized CheckpointTuple creation into a shared function for checkpoint_postgres

docs/docs/how-tos/persistence.ipynb
Hi, I think I found an error in the docs on the persistence page [Click here for reference in docs](https://langchain-ai.github.io/langgraph/how-tos/persistence/#use-in-production_1) and I fixed it
=> docs: fixed a wrong import in persistence docs

libs/langgraph/langgraph/graph/state.py, libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/loop.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py
- Split out superstep finish into separate after_tick() method
- Handle input in __enter__
- Remove unnecessary recursive shortcut
- Remove input sentinel objects
=> PregelLoop: Simplify tick() method

docs/_scripts/add_translation.py, docs/_scripts/generate_llms_text.py, docs/_scripts/link_map.py, docs/_scripts/notebook_hooks.py, docs/overrides/language-switcher.css, docs/overrides/language-switcher.js, docs/overrides/partials/language-toggle.html, docs/tests/unit_tests/test_conditional_rendering.py
Adding conditional rendering logic to co-locate js and python documentation.
* `:::` conditional syntax can be used to switch between python only or js only content.
* Contains simple unit tests for `:::`
* PR adds set up for a way to implement a context switch between languages, but it will not be enabled until JS content is merged in.
* Contains a script that can add javascript documentation 
Implementation of: https://github.com/langchain-ai/langgraph/pull/5118
Example of conditional rendering / compilation.
```markdown
Config is for immutable data like user metadata or API keys. Use
when you have values that don't change mid-run.
Specify configuration using a key called **"configurable"** which is reserved
for this purpose:
:::python
This content will only be rendered for the python …
```
=> docs: Add conditional js/python rendering

docs/_scripts/notebook_hooks.py
This PR fixes a typo found in claude-code/langgraph/docs/_scripts/notebook_hooks.py.
=> docs: fix a typo 'prebuit' to 'prebuilt' in notebook_hooks.py

libs/langgraph/langgraph/pregel/__init__.py
- update_state(None, as_node=None) was not tested/used, and was too similar in behavior to __copy__ / __end__, so removing it
=> Remove unused branch in update_state

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/model.py, libs/prebuilt/tests/test_react_agent.py
Make it easier to bind a model with builtin/interwoven tools in create_react_agent
=> fix: [prebuilt] Checks for pre-bound model with builtin tools

libs/sdk-js/package.json, libs/sdk-js/src/client.ts, libs/sdk-js/src/react/stream.tsx
Similar to #5208 we do want to avoid stale client when fetching `/history`. Use our best attempt to serialize the user provided client config.
=> fix(sdk-js): avoid stale client when fetching history

docs/docs/cloud/deployment/self_hosted_data_plane.md
One of the requirements for self-hosted data plane is that egress is enabled to the control plane. This was not explicit in our docs.
=> docs: Add pre-req for egress to control plane

docs/docs/cloud/how-tos/use_stream_react.md, libs/sdk-js/src/client.ts, libs/sdk-js/src/react/stream.tsx, libs/sdk-js/src/tests/sse.test.ts, libs/sdk-js/src/tests/stream.test.tsx, libs/sdk-js/src/utils/sse.ts
Adds three new options to the `useStream` React hook to improve user experience in common chat application scenarios:
- **`initialValues`**: Display cached thread data immediately while history loads
- **`newThreadId`**: Enable optimistic thread creation with predetermined IDs  
- **`onStop`**: Customize UI behavior when streams are stopped/cancelled
- Shows cached thread data instantly when navigating to existing threads
- Improves perceived performance by eliminating loading states for cached content
- Values priority: `streamValues > initialValues > historyValues`
- Backward compatible
- Enables optimistic UI patterns for thread creation
- Prevents 404 errors when automatically fetching thread history when navigating to routes before thread exists
- Allows predetermined thread IDs for …
=> feat(react): enhance useStream with initialValues, newThreadId, and onStop callback for improved UX

docs/docs/concepts/application_structure.md
This pull request includes minor corrections to comments in the `docs/docs/concepts/application_structure.md` file. Specifically, it fixes a small typographical error in the comments for Python and JavaScript directory structure examples. 
No functional changes were made. 
Changes:
* Fixed a typo in the comment for the `nodes.py` file in the Python directory structure example (`you graph` → `your graph`).
* Fixed a typo in the comment for the `nodes.ts` file in the JavaScript directory structure example (`you graph` → `your graph`).
=> docs: fix typo in application_structure

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py, libs/checkpoint-sqlite/tests/test_aiosqlite.py, libs/checkpoint-sqlite/tests/test_sqlite.py, libs/checkpoint/README.md, libs/checkpoint/langgraph/checkpoint/base/__init__.py, libs/checkpoint/tests/test_memory.py
Usage removed long ago (like a year) in https://github.com/langchain-ai/langgraph/commit/d9854b36ebb6690a5106ad73a3099ef3ee386259
=> langgraph: remove support for `thread_ts` (old alias for `checkpoint_id`)

.github/workflows/_integration_test.yml, .github/workflows/_lint.yml, .github/workflows/_test.yml, .github/workflows/_test_langgraph.yml, .github/workflows/baseline.yml, .github/workflows/bench.yml, .github/workflows/ci.yml, .github/workflows/link_check.yml, .github/workflows/release.yml, .github/workflows/release_js.yml, .github/workflows/run_notebooks.yml
* We're using restricted GITHUB_TOKENS by default.
* This is expected to be a no-op operation to appease codeql.
=> ci: set explicit workflow permissions to read (should be a no-op)

docs/docs/tutorials/get-started/1-build-basic-chatbot.md
The tutorial states a wrong (outdated) name of the type that's returned by `.compile()`
The name (and type) has changed. 
See: https://langchain-ai.github.io/langgraph/reference/graphs/#langgraph.graph.state.StateGraph.compile
=> docs: update name of CompiledGraph CompiledStateGraph

docs/docs/tutorials/multi_agent/hierarchical_agent_teams.ipynb, docs/docs/tutorials/multi_agent/multi-agent-collaboration.ipynb
The class `TavilySearchResults` was deprecated in LangChain 0.3.25 and will be removed in 1.0
=> dcos: Fix deprecation of TavilySearch

docs/docs/cloud/quick_start.md
A minor change to the curl command in the quick start guide that are needed to make the command work out of the box. I hope by adding these changes then new users can get started more quickly
=> docs: Update quick_start.md Rest API Guide

docs/docs/how-tos/memory/add-memory.md
This snagged me for a little bit, not sure if there is a reason to not have this in there.
When using persistence layers with JSON serde, the running_summary is a plain dict instead of a dataclass. If you're using a Pydantic state then adding this in will automatically handle proper deserialization.
This leaves a bit of hole in the docs, because the examples are using TypedDict classes, maybe there is an additional improvement we can add for that (but maybe it's out of scope). At the very least this provides a type hint of what's missing.
=> Updated examples for SummarizationNode to account for serde with persistence layers

docs/docs/cloud/reference/env_var.md
1. Add `RESUMABLE_STREAM_TTL_SECONDS` to environment variables page.
1. Reorder environment variables page headings to be in alphabetical order.
=> docs: Add `RESUMABLE_STREAM_TTL_SECONDS` to env vars list

libs/langgraph/langgraph/pregel/__init__.py, libs/langgraph/langgraph/pregel/protocol.py
You can call `invoke` / `stream` with a `Command` instance or `None` for resuming post error, so we should support those hints as well.
=> patch[langgraph]: Fix hint for `invoke`/`stream` to allow for `Command` and `None`

libs/langgraph/langgraph/graph/state.py
fix incorrect usage.
replace `_state_schema` to `state_schema` in CompiledStateGraph.attach_node
=> fix: replace _state_schema to state_schema when accessing StateGraph

docs/overrides/main.html
Somehow the link isn't working well,
in prod it's now linking to https://langchain-ai.github.io/llms-txt-overview/
while it should be https://langchain-ai.github.io/langgraph/llms-txt-overview/
=> fix: llm.txt url link broken 

docs/docs/concepts/low_level.md
Avoid confusion to readers. The code had `time.sleep(2)` but the note mentioned `one second` only.
The link to documentation : https://langchain-ai.github.io/langgraph/concepts/low_level/#node-caching
=> fix(docs): Node caching explanation code required a small fix,.

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py
- Channels containing primitive values don't need to be stored in separate rows in blobs table, as the overhead of a separate row will usually be higher than the size of the value
- This applies for instance to all internal channels used to manage edges, so it has a big impact just from that. It can also apply to user-managed channels depending on their values
- The same channel may switch storage between versions without any issue
=> perf(checkpoint-postgres): Reduce writes to checkpoint_blobs table

docs/docs/cloud/reference/env_var.md
- **Description:** add docs disclaimer that the DD_API_KEY provided to LangGraph Server can override code-level auto-instrumentation such as otel
=> docs(docs): add disclaimer about overriding otel with DD_API_KEY

libs/checkpoint/langgraph/store/base/batch.py, libs/checkpoint/tests/test_store.py
This commit fixes #5503
Gist of it is:
- `asyncio.exception.InvalidStateError` were being raised when the future was cancelled
- this exception bubbled up and killed the background task
- `AsyncBatchedBaseStore` stopped doing queries because the background task wasn't running anymore
This commit adds some "if future is not done" checks to guard against this.
=> fix(checkpoint): fix AsyncBatchedBaseStore getting stuck

docs/docs/cloud/reference/cli.md
Fix for wrong indentation that completely messes up formatting
=> fix(docs): fix langgraph cli reference

docs/docs/how-tos/autogen-integration.md
Hey there! This is AG2 👋
First of all, thank you for using pyautogen! We've seen you're using pyautogen, and we're here to help you migrate to ag2.
This pull request is designed to help update this codebase by smoothly transitioning from the `pyautogen` library to the new `ag2` library.
Why the change? `pyautogen` is being deprecated, and `ag2` is now the recommended successor for ongoing development. 
The good news is, **there is no syntax difference between pyautogen and ag2** – this migration primarily involves updating library imports and usage.
This update will ensure the project stays compatible with the latest tools and can benefit from all the improvements in the ag2 ecosystem.
Could you please take a moment to review and merge this at your earliest convenience? Your collaboration …
=> chore(docs): Migrate from pyautogen to ag2 Library

libs/langgraph/langgraph/pregel/remote.py
- when receiving a "command" stream event raise ParentCommand exception for caller graph to handle
=> feat(langgraph): Handle ParentCommand in RemoteGraph

libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/test_react_agent.py
Proposal for allowing to switch models and model configuration (including tools) at run time.
```python
def create_react_agent(
model: Union[
str, 
LanguageModelLike,
Callable[[SateLike, Runtime...], BaseChatModel], # <--- New
],
tools: Union[
Sequence[Union[BaseTool, Callable, dict[str, Any]]], ToolNode]
],
*,
....
llm = init_chat_model(...)
def prepare_model(state, runtime):
selected_tool_names = func(state, context)
return llm.bind(tools=selected_tool_names)
create_react_agent(
prepare_model,
tools=all_known_tools
)
```
1. `tools` = are the known tools, used to configure ToolNode and will configure:
1. model provided as string
2. model provided as BaseChatModel (if it has no tools bound to it)
2. If a user provides a dynamic model (callable), the user is responsible for binding tools …
=> feat(prebuilt): Add dynamic model to create_react_agent

libs/langgraph/langgraph/utils/config.py, libs/langgraph/utils/__init__.py, libs/langgraph/utils/config.py, libs/langgraph/utils/runnable.py
Don't need top level file, just `langgraph.utils`
=> fix(langgraph): backwards compat config utils

docs/docs/agents/context.md
clarifying difference between runtime context and llm context window. inspired by https://openai.github.io/openai-agents-python/context/
=> fix(docs): clarify value of context

libs/langgraph/langgraph/pregel/main.py, libs/langgraph/tests/test_runtime.py
Fixes https://github.com/langchain-ai/langgraph/issues/5700
I also considered an `override_if_not_none` but merge does that
=> fix(langgraph): always use parent runtime info if available

libs/langgraph/langgraph/_internal/_runnable.py, libs/langgraph/tests/test_runnable.py
Fixes https://github.com/langchain-ai/langgraph/issues/5698
I would like to do a more general refactor of this logic at some point as well using typing introspection utilities. Claude code first pass: https://github.com/langchain-ai/langgraph/pull/5709
=> fix(langgraph): enforce config injection even when optional

docs/_scripts/notebook_hooks.py
Add a redirect from https://langchain-ai.github.io/langgraph/troubleshooting/studio/ to https://docs.langchain.com/langgraph-platform/troubleshooting-studio
=> docs: Add studio troubleshooting to redirects

libs/langgraph/langgraph/errors.py, libs/langgraph/langgraph/pregel/main.py, libs/langgraph/langgraph/types.py, libs/langgraph/tests/test_deprecation.py
Fixes https://github.com/langchain-ai/langgraph/issues/5795
* Must use `category=None` on decorator so that we get type checking support but no dupe warning
* Fixed tuple on `config_type` warning causing false warning
=> fix(langgraph): fix up deprecation warnings

libs/langgraph/langgraph/pregel/_messages.py, libs/langgraph/langgraph/pregel/main.py, libs/langgraph/tests/test_pregel.py, libs/langgraph/tests/test_pregel_async.py, libs/prebuilt/tests/test_react_agent.py
Reproduces: https://github.com/langchain-ai/langgraph/issues/5249#issuecomment-3156519635
Caused after this change: https://github.com/langchain-ai/langgraph/pull/4843
Fix to allow emitting messages from subgraphs if the subgraphs explicitly used a stream mode "messages".
```python
def node_in_parent(...):
for event in subgraph.stream(..., stream_mode="messages"):
return ...
parent_graph.invoke(..., subgraphs=False)
```
The code above should continue to work correctly regardless of the value of subgraphs as streaming messages was requested explicitly in the parent node!
=> fix(langgraph): support emitting messages from subgraphs when messages mode explicitly requested

libs/prebuilt/langgraph/prebuilt/_internal/_typing.py, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/test_react_agent.py
Do not support prebound tools on the model. There's reason users should be prebinding tools to the model!
This is a breaking change that might affect some users, but the work-around is simple -- provide tools into the create_react_agent api.
=> chore(prebuilt): breaking do not support prebound tools on model

libs/prebuilt/langgraph/prebuilt/_internal/_typing.py, libs/prebuilt/langgraph/prebuilt/chat_agent_executor.py, libs/prebuilt/tests/test_react_agent.py
Remove support for models w/ `.bind` used to streamline public API + recommendations
Also cleaning up `typing.py` file as requested :)
=> chore(prebuilt): remove support for models that used `bind_X`

libs/prebuilt/langgraph/prebuilt/tool_node.py, libs/prebuilt/tests/test_tool_node.py
This PR extends the `ToolNode` `handle_tool_errors` property to also accept a single exception type: `type[Exception]`.
Example:
```python
tool_node_with_error_handling = ToolNode(
[tool1, tool2, tool3], handle_tool_errors=ValueError
).invoke(...)
"""A tool node that will only retry a failed tool call if a ValueError is raised"""
```
=> feat(prebuilt): add support for handle_tool_errors with single exception type

docs/docs/cloud/reference/api/openapi.json
This PR updates the OpenAPI specification with changes detected from the LangGraph API server.
**Changes detected as of LangGraph API version 0.4.9**
This update was automatically generated by the sync workflow in the langgraph-api repository.
=> chore(docs): Update OpenAPI spec from LangGraph API v0.4.9

docs/docs/cloud/reference/api/openapi.json
This PR updates the OpenAPI specification with changes detected from the LangGraph API server.
**Changes detected as of LangGraph API version 0.4.11**
This update was automatically generated by the sync workflow in the langgraph-api repository.
=> chore(docs): Update OpenAPI spec from LangGraph API v0.4.11

docs/docs/concepts/memory.md
- **Description:** Fix the wrong variable name in the example of `memory.md`.
- **Dependencies:** NA.
=> docs (langgraph): Fix bug in the code example

docs/docs/tutorials/workflows.md
Description:
The documentation for the should_continue function contained an incorrect return type annotation.
It was shown as Literal["environment", END], but the actual logic returns "Action" or END.
This PR updates the example to use Literal["Action", END] so that the documentation matches the intended behavior of the function.
Issue:
N/A
Dependencies:
None
=> docs(docs): fix incorrect return type in should_continue example

libs/checkpoint-postgres/tests/test_store.py, libs/checkpoint-sqlite/tests/test_store.py, libs/checkpoint/langgraph/store/base/embed.py, libs/checkpoint/tests/test_redis_cache.py, libs/checkpoint/tests/test_store.py
* Set `ensure_ascii=False` for all `json.dumps` calls in `get_text_at_path`. Preserves non-ASCII text instead of embedding `\uXXXX` escapes. 
**Before**
```python
store.put(("user_123", "memories"), "1", {"text": "这是中文"})
```
**After**
```python
store.put(("user_123", "memories"), "1", {"text": "这是中文"})
```
* Add unit test `test_non_ascii` that writes three records (Chinese, Japanese, Korean) to an `InMemoryStore`, searches with the same strings, and asserts the correct top hit with a score >= 0.15 for each.
Fixes #5946
=> fix(checkpoint): preserve non-ascii text in InMemoryStore embeddings

libs/langgraph/langgraph/_internal/_config.py, libs/langgraph/tests/test_utils.py
Right now we include configuration as metadata (which is later passed to tracing callbacks).
Right now we include any key that doesn't have a dunder prefix and whose value is a string or int.
This PR proposes to also exclude keys with certain substrings (key, secret, token).
I would also be in favor of dropping support for forwarding configurable values to metadata entirely, but this is a smaller, less controversial change.
Add a test.
=> chore(langgraph): Omit other keys from metadata by default

libs/cli/langgraph_cli/docker.py, libs/cli/tests/unit_tests/test_docker.py
Description:
Corrects _parse_version to support Docker versions with SemVer build metadata (e.g., 28.1.1+1), resolving #5965. Adds comprehensive unit tests for version parsing, including normal, v-prefixed, prerelease, build metadata, combined prerelease/build metadata, and edge cases with missing components.
Issue:
Closes #5965
Dependencies:
None
=> fix(cli): handle Docker SemVer build metadata in version parsing #5965

libs/langgraph/langgraph/graph/ui.py
**Description:**
This PR adds missing documentation for the `merge` parameter in the `push_ui_message` function. The parameter was    present in the function signature but lacked documentation in the docstring, which could confuse API users.
Changes made:
- Added clear documentation for the `merge` parameter
- Explains the behavior difference between `merge=True`
(merges props) and `merge=False` (replaces props)
- Includes default value information
**Issue:**
N/A - Documentation improvement
**Dependencies:**
None
=> docs: Add missing merge parameter documentation in push_ui_message

libs/checkpoint/tests/test_store.py
`test_embed_with_path` was failing on x86_64 architecture due to numeric precision differences. `pytest.approx` was already used later on in this test for float comparison, so this PR just updates a missed assertion.
Fixes https://github.com/langchain-ai/langgraph/issues/5845
=> fix(checkpoint): use tolerant float comparison to fix test failing on x86_64 architecture

libs/langgraph/langgraph/pregel/_loop.py, libs/langgraph/tests/test_pregel.py
**Description**: fix #6050. 
Root cause: In nested graphs, the first tick after resume often included a checkpoint_id, which set skip_done_tasks=False. This skipped matching pending writes and re-executed already-completed helper @task on subsequent resumes.
Change: Initialize skip_done_tasks=True when resuming inside a nested graph. Use original config[CONF] for checkpoint_id presence, and self.config[CONF] for resuming (current loop state). Added a concise comment clarifying the different config sources.
**Issue**: #6050 
**Tests**: 
Add regression test `test_nested_graph_resume_reuses_cached_task_writes`
=> fix(langgraph): reuse cached writes on nested resume to prevent task re-execution

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py
https://github.com/langchain-ai/langgraph/issues/6137 and https://github.com/langchain-ai/langgraph/issues/5677 reported issues where older checkpoints read by AsyncPostgresSaver/PostgresSaver from `langgraph-checkpoint-postgres==2.0.19` fail to read channel values, throwing `NoneType object is not a mapping`. This was due to a bug in how `channel_values` is assembled:
```python
"channel_values": {
**value["checkpoint"].get("channel_values"),  # <--- if channel_values doesn't exist (old checkpoint), **None errors
**self._load_blobs(value["channel_values"]),
},
```
This bug was observed for checkpoints generated by `langgraph-checkpoint-postgres<=2.0.19`.
Fixed by providing a fallback to `value["checkpoint"].get("channel_values")`:
```python
**value["checkpoint"],
"channel_values": {
**( …
```
=> fix(langgraph): fix PostgresSaver crashing when loading older checkpoints

libs/sdk-py/langgraph_sdk/auth/__init__.py, libs/sdk-py/langgraph_sdk/client.py
- When connection is dropped while waiting, reconnect up to 5 times if a Location header is present
=> feat: sdk-py: Reconnect to long-lived responses on wait/join/cancel endpoints

docs/README.md, libs/langgraph/pyproject.toml
Each of the settings present are already defaults in the ruff config:
https://docs.astral.sh/ruff/settings/
=> chore(langgraph): clean up ruff format config

libs/sdk-py/langgraph_sdk/auth/types.py
The `$contains` auth operator supports subset containment checks, but this has previously been undocumented. This updates `FilterType` and its associated docstring to reflect this support.
=> chore(sdk-py): refine FilterType, add subset containment to $contains docs

libs/langgraph/langgraph/pregel/debug.py
This adds `StateSnapshot` to the union type annotation of `CheckpointTask.state`. 
The annotation was previously incomplete: `map_debug_checkpoint()` generates `CheckpointPayload` objects from `PregelTask` objects, and the `state` field in `PregelTask`  is of type `None | RunnableConfig | StateSnapshot`.
=> fix(langgraph): `CheckpointTask.state` can be a `StateSnapshot`

libs/langgraph/langgraph/graph/state.py, libs/langgraph/tests/test_state.py
This PR ensures that even if a type has multiple annotations, we can still detect the `BaseChannel` subclasses attached.
```py
class State(TypedDict):
foo: Annotated[int, EphemeralValue]
bar: Annotated[int, EphemeralValue, OtherMetadata]
baz: Annotated[int, SomeMetadata, EphemeralValue, OtherMetadata]
```
=> fix(langgraph): handle multiple annotations w/ `BaseChannel` detection

libs/langgraph/langgraph/pregel/debug.py, libs/langgraph/tests/test_large_cases.py, libs/langgraph/tests/test_large_cases_async.py, libs/langgraph/tests/test_pregel.py
Overview
Python port of https://github.com/langchain-ai/langgraphjs/pull/1551
Introduces `map_task_result_writes` to standardize task result format across `get_state_history` and `map_task_result_writes` response structures.
Solves https://github.com/langchain-ai/langgraph/issues/6073
=> fix(langgraph): task result from stream mode debug / tasks should match format from get_state_history / get_state

libs/checkpoint-postgres/langgraph/checkpoint/postgres/__init__.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/aio.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/base.py, libs/checkpoint-postgres/langgraph/checkpoint/postgres/shallow.py, libs/checkpoint-postgres/tests/test_async.py, libs/checkpoint-postgres/tests/test_sync.py, libs/checkpoint/langgraph/checkpoint/base/__init__.py
Issue
Support for `Checkpoint.metadata.writes` was dropped in `langgraph` v0.5.x. 
In `langgraph-checkpoint-postgres` v2.0.23, metadata was serialized with `BasePostgresSaver._dump_metadata` -> `JsonPlusSerializer.dumps` which handles `pydantic.BaseModel`.
In v2.0.23, metadata is serialized with `psycopg.types.json.Jsonb`, which raises `TypeError: Object of type AIMessage is not JSON serializable` when trying to serialize `writes`.
Solution
- Add `BaseCheckpointSaver.get_serializable_checkpoint_metadata` which pops the `writes` key. 
- Log deprecation warning when strange version combinations are used 
Solves https://github.com/langchain-ai/langgraph/issues/5769
=> fix(checkpoint): handle metadata.writes when serializing old checkpoints with Jsonb

libs/langgraph/langgraph/pregel/_loop.py, libs/langgraph/langgraph/pregel/main.py, libs/langgraph/tests/test_interruption.py
Prevents interrupt tasks from executing when the resume value has not yet been specified.
Implemented for sync and async Pregel loop
If a task execution is skipped, the skipped interrupt is still included in the graph result for consistency:
``` python
result = graph.invoke(...)
interrupts = result.get("__interrupt__", [])   # [interrupt_1, interrupt_2]
partial_result = graph.invoke(Command(resume=interrupt_1_resume_map), ...)
remaining_interrupts = partial_result.get("__interrupt__", [])  # [interrupt_2]
```
- `test_interrupt_with_send_payloads`: test for a single resume map that resumes all interrupts at once
- `test_interrupt_with_send_payloads_sequential_resume`: test for two resume maps delivered in sequence
- `test_node_with_multiple_interrupts_requires_full_resume` test …
=> fix(langgraph): selective interrupt task scheduling

libs/checkpoint-postgres/pyproject.toml, libs/checkpoint-postgres/uv.lock, libs/checkpoint-sqlite/uv.lock, libs/checkpoint/pyproject.toml, libs/checkpoint/uv.lock, libs/langgraph/uv.lock, libs/prebuilt/uv.lock
- Bump `langgraph-checkpoint` to 2.1.2
- Bump `langgraph-checkpoint-postgres` to 2.0.25 and raise `langgraph-checkpoint` dep lower bound to 2.1.2
=> chore(checkpoint): bump patch version

libs/cli/langgraph_cli/cli.py
begin process of renaming Studio to Debugger
keep --studio-url around for now as an option as well
=> fix(cli): rename studio to debugger
